package curriculum

var goalSubpatternSpecsVisualDigitalWriting = map[string]goalSubpatternSpec{
	"writing_storytelling:presentation_publish:brunch_serial_publish": {
		Name:                    "브런치/연재 공개형",
		StepRoles:               []string{"first_output", "structure_plan", "integration_practice", "publish_prep"},
		StageRules:              []string{"리슨은 글 한 편의 완성에서 끝나지 않고 글 묶음과 연재 흐름 정리로 이어져야 합니다.", "독자 흐름, 주제 흐름, 묶음 구조가 드러나는 단계가 포함되어야 합니다."},
		LastLessonRule:          "마지막 lesson은 발행 직전까지 글 묶음과 공개 흐름을 다듬는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 브런치 발행, 연재 시작, 공개 게시 자체는 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"맞춤법만 보기", "문장 이론 설명"},
	},
	"writing_storytelling:habit_lifestyle:daily_writing_habit": {
		Name:                    "매일 글쓰기 루틴형",
		StepRoles:               []string{"setup_intro", "first_output", "integration_practice"},
		StageRules:              []string{"리슨은 출간형 구조보다 부담 없이 반복 가능한 글쓰기 단위를 만드는 흐름에 초점을 둡니다.", "짧은 기록, 반복 가능한 단위, 지속 가능한 빈도가 자연스럽게 이어져야 합니다."},
		LastLessonRule:          "마지막 lesson은 지속 가능한 글쓰기 루틴을 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"매일 쓰기 유지 자체는 completion_criteria로 분리할 수 있습니다."},
		AtomicDisallowExamples:  []string{"문장 이론 설명", "맞춤법만 보기"},
	},
	"visual_art:artifact_creation:watercolor_beginner_landscape": {
		Name:                    "수채화 풍경 엽서 입문형",
		StepRoles:               []string{"setup_intro", "first_output", "core_pattern", "integration_practice", "artifact_finish"},
		StageRules:              []string{"리슨은 물감과 종이 소개만으로 분리하지 말고 물 조절, 번짐·그라데이션, 간단한 하늘과 나무, 작은 풍경 엽서 완성 흐름으로 이어져야 합니다.", "초보 수채화 목표에서는 정교한 묘사보다 물 농도, 색 번짐, 레이어 건조, 작은 풍경 구성의 반복 가능한 감각을 우선합니다."},
		LastLessonRule:          "마지막 lesson은 작은 수채화 풍경 엽서 한 점을 완성하고 물 조절, 번짐, 구도, 마감 상태를 점검하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"작품 공개, 판매, 전시, 고급 인물화나 정물화는 completion_criteria 또는 후속 목표로 분리합니다."},
		AtomicDisallowExamples:  []string{"물감 색만 고르기", "붓 종류만 보기", "종이 비교만 하기"},
	},
	"visual_art:artifact_creation:calligraphy_basic_lettering": {
		Name:                    "캘리그라피 기본 손글씨형",
		StepRoles:               []string{"setup_intro", "first_output", "core_pattern", "artifact_finish"},
		StageRules:              []string{"리슨은 도구 소개만으로 분리하지 말고 붓펜 잡기, 선의 굵기 변화, 자모·획 연습, 단어 쓰기를 한 흐름으로 연결해야 합니다.", "초보 목표에서는 한 글자·한 단어·짧은 문장처럼 작은 결과물이 빠르게 나오도록 구성합니다."},
		LastLessonRule:          "마지막 lesson은 한 단어 또는 짧은 문구를 안정적인 손글씨 결과물로 완성하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"기본 손글씨 연습 기록 제출은 completion_criteria로 분리할 수 있습니다.", "문장 작품 제작, 실제 전시나 SNS 공개는 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"붓펜 종류만 보기", "선긋기만 하기", "자음 하나만 쓰기"},
	},
	"visual_art:artifact_creation:calligraphy_quote_art_project": {
		Name:                    "캘리그라피 문구 작품 제작형",
		StepRoles:               []string{"setup_intro", "structure_plan", "core_pattern", "integration_practice", "artifact_finish"},
		StageRules:              []string{"리슨은 글씨 연습에서 끝나지 않고 문구 선택, 글자 크기와 여백, 배경·장식, 카드·엽서 마감까지 이어져야 합니다.", "명언·문장·엽서 목표는 가독성과 감정 전달, 구도 안정성을 함께 점검하는 단계가 필요합니다."},
		LastLessonRule:          "마지막 lesson은 선물하거나 보관할 수 있는 캘리그라피 문구 작품 한 점을 완성하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"완성 작품 촬영과 간단한 제작 기록은 completion_criteria로 분리할 수 있습니다.", "판매나 의뢰 수주는 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"명언 고르기만 하기", "배경색만 칠하기", "글자 크기만 비교하기"},
	},
	"visual_art:presentation_publish:calligraphy_publish_showcase": {
		Name:                    "캘리그라피 공개·게시형",
		StepRoles:               []string{"first_output", "core_pattern", "integration_practice", "publish_prep"},
		StageRules:              []string{"리슨은 한 장 완성에서 끝나지 않고 공개할 작품 묶음, 사진 촬영, 제목·설명, 게시 순서 정리로 이어져야 합니다.", "공개 목표에서는 작품 스타일의 일관성과 보는 사람이 이해할 소개 문구를 함께 준비합니다."},
		LastLessonRule:          "마지막 lesson은 SNS나 공개 플랫폼에 올리기 직전까지 작품 묶음과 소개 흐름을 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 SNS 업로드와 공개 게시 자체는 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"해시태그만 정하기", "사진 필터만 고르기", "작품 한 장만 급히 쓰기"},
	},
	"visual_art:presentation_publish:art_publish_showcase": {
		Name:                    "전시/인스타 공개형",
		StepRoles:               []string{"first_output", "core_pattern", "integration_practice", "publish_prep"},
		StageRules:              []string{"리슨은 재료 소개보다 공개 가능한 작품 묶음과 소개 흐름 정리에 초점을 둡니다.", "작품 한 점 완성에서 끝내지 말고 공개용 정리 단계까지 이어져야 합니다."},
		LastLessonRule:          "마지막 lesson은 공개 직전까지 작품 묶음과 소개 흐름을 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 전시 오픈과 인스타 업로드는 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"재료 소개", "붓 설명", "색 이론 설명"},
	},
	"visual_art:certification_assessment:beauty_service_practical_certification": {
		Name:                    "메이크업 실기 자격형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "performance_prep"},
		StageRules:              []string{"리슨은 이론 설명보다 공개과제 표현 순서와 결과물 완성 흐름에 초점을 둡니다.", "도구와 재료 설명은 독립 리슨이 아니라 실기 과제 단계 안에 흡수되어야 합니다."},
		LastLessonRule:          "마지막 lesson은 실기 시험 직전까지 표현 순서와 시간 배분을 점검하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 시험 응시와 자격 취득은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"도구 소개만 보기", "색조 이론만 보기"},
	},
	"digital_creation:presentation_publish:portfolio_publish": {
		Name:                    "포트폴리오/업로드 공개형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "publish_prep"},
		StageRules:              []string{"리슨은 영상편집, 디지털 콘텐츠, 디자인 결과물 같은 공개 가능한 결과물 품질과 게시 흐름 정리에 초점을 둡니다.", "완성만으로 끝내지 말고 유튜브·포트폴리오·릴스·쇼츠 같은 공개 포맷, 게시 설명, 썸네일/대표 이미지, 업로드 직전 점검 단계까지 이어져야 합니다."},
		LastLessonRule:          "마지막 lesson은 영상·디자인·디지털 결과물을 유튜브, 포트폴리오, 릴스, 쇼츠, 공개 페이지에 게시하기 직전까지 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 업로드, 유튜브 공개, 포트폴리오 게시, 릴스 공개는 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"툴 인터페이스 설명만 보기", "단축키 소개만 보기"},
	},
	"digital_creation:teaching_instruction:creator_tutorial_publish": {
		Name:                    "디지털 제작 튜토리얼형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "artifact_finish", "teaching_prep"},
		StageRules:              []string{"리슨은 툴 설명만 나열하지 말고 강의 영상 주제 선정, 촬영 구성, 제작 예시, 설명 스크립트, 편집·게시 직전 준비로 이어져야 합니다.", "내가 아는 취미 기술이나 디지털 제작 과정을 다른 사람이 따라 할 수 있는 튜토리얼 영상 흐름으로 정리해야 합니다."},
		LastLessonRule:          "마지막 lesson은 짧은 강의 영상이나 튜토리얼 콘텐츠를 촬영·편집하고 게시 직전까지 설명 흐름을 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 튜토리얼 업로드와 강의 공개는 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"툴 소개만 보기", "단축키 설명만 보기"},
	},
	"digital_creation:artifact_creation:video_editing_shortform_project": {
		Name:                    "숏폼 영상 편집 프로젝트형",
		StepRoles:               []string{"setup_intro", "first_output", "core_pattern", "integration_practice", "artifact_finish"},
		StageRules:              []string{"리슨은 편집툴 메뉴 설명만 나열하지 말고 소스 정리, 첫 컷편집, 자막·음악·전환, 세로 화면 구성, 최종 내보내기 흐름으로 이어져야 합니다.", "숏폼 목표에서는 조회수 전략보다 초보자가 직접 완성 가능한 30~60초 영상의 편집 품질과 포맷 점검을 우선합니다."},
		LastLessonRule:          "마지막 lesson은 쇼츠·릴스 형식의 짧은 영상을 내보내기 직전까지 자막, 사운드, 화면 비율, 컷 흐름을 점검하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 유튜브·인스타 업로드와 공개 반응 확인은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"툴 설치만 하기", "효과 하나만 적용하기", "단축키만 외우기"},
	},
	"digital_creation:artifact_creation:freeware_midi_beatmaking": {
		Name:                    "무료 DAW MIDI 첫 비트 제작형",
		StepRoles:               []string{"setup_intro", "first_output", "core_pattern", "artifact_finish"},
		StageRules:              []string{"리슨은 무료 도구 가입이나 설치만으로 분리하지 말고 첫 드럼 패턴과 MIDI 노트 입력까지 빠르게 연결해야 합니다.", "초보 목표에서는 BandLab, LMMS, TunePad 같은 무료 도구로 짧은 beat 결과물이 나오도록 구성합니다."},
		LastLessonRule:          "마지막 lesson은 무료 도구에서 짧은 beat 한 개를 완성하고 재생·저장 상태를 점검하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"완성 beat 파일 export나 공유는 completion_criteria로 분리할 수 있습니다.", "유료 플러그인 구매나 배포 수익화는 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"DAW 가입만 하기", "버튼 이름만 보기", "드럼 샘플만 고르기"},
	},
	"digital_creation:artifact_creation:freeware_midi_full_track": {
		Name:                    "무료 DAW MIDI 전체 트랙 완성형",
		StepRoles:               []string{"setup_intro", "first_output", "core_pattern", "integration_practice", "artifact_finish"},
		StageRules:              []string{"리슨은 loop 반복에서 끝나지 않고 드럼, 베이스, 코드, 멜로디, arrangement, effects, automation, export 준비로 이어져야 합니다.", "도구 기능 설명은 독립 리슨보다 트랙 완성에 필요한 제작 관문 안에 흡수합니다."},
		LastLessonRule:          "마지막 lesson은 무료 도구에서 짧은 곡 또는 전체 트랙을 export 직전 상태까지 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 음원 공개, 플랫폼 업로드, 배포는 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"export 버튼만 보기", "EQ 이름만 보기", "loop만 반복 배치하기"},
	},
	"digital_creation:artifact_creation:midi_foundation_workflow": {
		Name:                    "MIDI 기초 워크플로우형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "artifact_finish"},
		StageRules:              []string{"리슨은 MIDI 정의 암기보다 MIDI가 소프트웨어 악기와 컨트롤러를 어떻게 움직이는지 실제 연결 흐름으로 설명해야 합니다.", "기초 목표라도 마지막에는 간단한 MIDI phrase나 software instrument 재생 결과가 있어야 합니다."},
		LastLessonRule:          "마지막 lesson은 MIDI 송수신과 note 입력 흐름을 이용해 짧은 MIDI phrase를 만들고 재생하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"MIDI 컨트롤러 구매나 특정 장비 세팅 완료는 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"MIDI 정의만 외우기", "케이블 종류만 보기", "컨트롤러 제품 비교만 하기"},
	},
	"digital_creation:artifact_creation:vibe_coding_mvp_app": {
		Name:                    "바이브 코딩 MVP 앱 제작형",
		StepRoles:               []string{"setup_intro", "structure_plan", "first_output", "core_pattern", "artifact_finish"},
		StageRules:              []string{"리슨은 도구 가입이나 프롬프트 예시 학습에서 끝나지 않고, 아이디어를 PRD/요구사항으로 정리한 뒤 AI로 작동하는 첫 앱을 만들어야 합니다.", "초보 목표에서는 코드 문법 전체를 선행하지 말고 AI가 만든 결과를 읽고 수정하는 반복 흐름을 우선합니다."},
		LastLessonRule:          "마지막 lesson은 작은 앱 또는 MVP가 작동하고 핵심 사용자 흐름을 직접 점검하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 서비스 출시, 유료화, 앱스토어 제출은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"도구 가입만 하기", "프롬프트 예시만 읽기", "앱 아이디어만 나열하기"},
	},
	"digital_creation:artifact_creation:notion_study_dashboard": {
		Name:                    "Notion 학습 대시보드 제작형",
		StepRoles:               []string{"setup_intro", "structure_plan", "core_pattern", "integration_practice", "routine_plan"},
		StageRules:              []string{"리슨은 Notion 기능 소개만 나열하지 말고 학습 목적 정리, task database 설계, notes page 구조, weekly review template, 실제 한 주 사용 점검으로 이어져야 합니다.", "dashboard 목표에서는 예쁜 템플릿보다 과제, 노트, 복습이 연결되는 반복 가능한 학습 운영 흐름을 우선합니다."},
		LastLessonRule:          "마지막 lesson은 만든 study dashboard로 한 주 복습을 실행하고 다음 개선점을 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"유료 템플릿 판매, 팀 협업 운영, 고급 자동화는 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"템플릿만 복제하기", "아이콘 꾸미기만 하기", "database 이름만 만들기"},
	},
	"digital_creation:artifact_creation:vibe_coding_fullstack_ship": {
		Name:                    "바이브 코딩 full-stack 배포형",
		StepRoles:               []string{"setup_intro", "structure_plan", "core_pattern", "integration_practice", "artifact_finish", "publish_prep"},
		StageRules:              []string{"리슨은 UI 생성에서 끝나지 않고 frontend 구조, database/auth 연결, 오류 정리, 보안 점검, 배포 직전 정리까지 이어져야 합니다.", "AI가 만든 코드는 검토와 정리 단계를 반드시 거치며, 배포 버튼만 누르는 lesson을 만들지 않습니다."},
		LastLessonRule:          "마지막 lesson은 배포 직전까지 앱의 핵심 흐름, 데이터, 인증, 오류, 보안 상태를 점검하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 프로덕션 운영, 과금 연결, 사용자 확보는 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"컴포넌트 하나만 만들기", "DB 테이블명만 정하기", "deploy 버튼만 누르기"},
	},
	"digital_creation:artifact_creation:claude_code_agentic_workflow": {
		Name:                    "Claude Code agentic workflow형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "artifact_finish", "publish_prep"},
		StageRules:              []string{"리슨은 Claude Code 설치나 명령어 암기가 아니라 context engineering, 계획, 코드 변경, 테스트, hook/MCP/agent 자동화가 이어지는 workflow에 초점을 둡니다.", "고급 자동화는 작은 기능 변경을 안전하게 반복하는 흐름 위에 얹어야 합니다."},
		LastLessonRule:          "마지막 lesson은 Claude Code 기반 반복 개발 workflow를 작은 프로젝트에 적용하고 테스트·정리까지 마치는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 팀 도입, CI/CD 운영 전환, 프로덕션 배포는 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"Claude Code 설치만 하기", "slash command 목록만 보기", "MCP 이름만 외우기"},
	},
	"digital_creation:foundation_build:problem_set_to_final_project": {
		Name:                    "영어 problem set-final project형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "artifact_finish"},
		StageRules:              []string{"리슨은 problem set 번호를 그대로 복제하지 말고 컴퓨팅 사고, 핵심 CS 개념, 문제 해결 적용, final project 준비의 큰 관문으로 압축합니다.", "문제 제출은 독립 리슨이 아니라 개념을 실제 문제에 적용하는 활동으로 흡수합니다."},
		LastLessonRule:          "마지막 lesson은 final project를 설계하고 구현 직전 또는 작은 산출물 완성 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 problem set 제출, final project 제출, certificate 획득은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"problem set 제출만 하기", "개발환경 세팅만 하기", "문법 이름만 외우기"},
	},
	"digital_creation:artifact_creation:web_dev_project_foundation": {
		Name:                    "영어 웹 개발 프로젝트 기초형",
		StepRoles:               []string{"setup_intro", "first_output", "core_pattern", "integration_practice", "artifact_finish"},
		StageRules:              []string{"리슨은 개발 도구나 태그 암기보다 웹 동작 원리, 첫 페이지, HTML/CSS/JavaScript 핵심 패턴, 반복 프로젝트, 초급 포트폴리오 산출물로 이어져야 합니다.", "작은 프로젝트는 기능 조각보다 완성 가능한 사용자 흐름 단위로 묶습니다."},
		LastLessonRule:          "마지막 lesson은 초급 웹 프로젝트나 포트폴리오에 넣을 수 있는 작은 결과물을 완성하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"공개 배포, 취업 지원, full-stack 전환은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"Git 설치만 하기", "태그 이름만 외우기", "버튼 하나만 만들기"},
	},
	"digital_creation:foundation_build:web_platform_core_curriculum": {
		Name:                    "영어 web platform core curriculum형",
		StepRoles:               []string{"setup_intro", "first_output", "core_pattern", "integration_practice", "performance_prep"},
		StageRules:              []string{"리슨은 HTML, CSS, JavaScript, accessibility, tools를 따로 흩뜨리지 말고 첫 웹사이트와 실무형 best practice로 연결합니다.", "challenge나 test 하나는 독립 리슨이 아니라 각 기술 관문 안의 점검 활동으로 둡니다."},
		LastLessonRule:          "마지막 lesson은 접근성, 반응형, 도구 사용까지 포함해 실무 적용 직전 수준으로 점검하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"공식 평가 통과, 취업, 실제 서비스 운영은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"challenge 하나만 풀기", "test 하나만 보기", "API 이름 하나만 외우기"},
	},
	"digital_creation:professional_transition:frontend_competency_map": {
		Name:                    "영어 frontend competency map형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "performance_prep"},
		StageRules:              []string{"리슨은 직무 역량 항목을 나열하지 말고 초급 프론트엔드 개발자가 갖춰야 할 기술군과 best practice를 자기 점검 가능한 단위로 묶습니다.", "취업 자체보다 역량 기준을 실제 코드와 작업 흐름에 적용하는 준비 단계에 초점을 둡니다."},
		LastLessonRule:          "마지막 lesson은 job-ready 기준에 맞춰 부족한 역량과 다음 포트폴리오 과제를 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"취업 지원, 면접 합격, 실제 직무 전환은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"competency 항목 하나만 읽기", "직무명만 조사하기", "취업 자체를 lesson으로 만들기"},
	},
	"digital_creation:artifact_creation:creative_coding_visual_project": {
		Name:                    "영어 creative coding visual project형",
		StepRoles:               []string{"setup_intro", "first_output", "core_pattern", "integration_practice", "artifact_finish"},
		StageRules:              []string{"리슨은 shape 하나나 색상 선택 하나가 아니라 drawing output, shapes/color/interaction 패턴, challenge 반복, 작은 animation/project 완성으로 이어져야 합니다.", "초보 creative coding은 코드 개념이 바로 시각 결과물로 드러나야 합니다."},
		LastLessonRule:          "마지막 lesson은 간단한 drawing, animation, interaction project를 완성하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"작품 공개, 갤러리 게시, 장기 포트폴리오 운영은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"shape 하나만 그리기", "color picker만 쓰기", "challenge 하나만 제출하기"},
	},
	"digital_creation:artifact_creation:game_3d_guided_pathway": {
		Name:                    "영어 game/3D guided pathway형",
		StepRoles:               []string{"setup_intro", "first_output", "core_pattern", "integration_practice", "artifact_finish", "publish_prep"},
		StageRules:              []string{"리슨은 Unity 설치나 editor panel 설명만으로 분리하지 말고 첫 3D scene, scripting/gameplay 패턴, prototype 통합, portfolio 또는 publish 준비로 이어져야 합니다.", "XP와 badge는 학습 활동 확인이나 완료 기준으로 두고 lesson 경계는 결과물 관문으로 잡습니다."},
		LastLessonRule:          "마지막 lesson은 작은 gameplay prototype을 완성하고 공개 또는 포트폴리오 직전까지 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 출시, store 제출, 공식 badge 획득은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"Unity Hub 설치만 하기", "editor panel 이름만 보기", "badge 이름만 확인하기"},
	},
	"digital_creation:foundation_build:mooc_programming_foundation": {
		Name:                    "영어 MOOC 프로그래밍 기초형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "artifact_finish"},
		StageRules:              []string{"리슨은 MOOC 주차나 강의 제목을 그대로 복제하지 말고 프로그래밍 역할 이해, 핵심 개념·문법 패턴, 문제세트 적용, 작은 프로그램 산출물의 큰 관문으로 압축합니다.", "설치, 자료형 이름, quiz 제출은 독립 리슨이 아니라 문제해결 흐름 안의 활동으로 흡수합니다."},
		LastLessonRule:          "마지막 lesson은 핵심 개념을 작은 프로그램이나 문제해결 산출물로 통합하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 MOOC 수료, certification 발급, 별도 앱 출시는 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"Python 설치만 하기", "자료형 이름만 외우기", "quiz만 풀기", "problem set 제출만 하기"},
	},
	"digital_creation:professional_transition:learning_path_role_skill": {
		Name:                    "영어 role/skill learning path형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "performance_prep"},
		StageRules:              []string{"리슨은 제품 메뉴를 훑는 순서가 아니라 역할·기술 목표 선택, 핵심 module 순회, task scenario 적용, credential 또는 career path 직전 점검으로 구성합니다.", "공식 credential이 목표일 때는 certification_assessment와 섞지 말고 시험 응시 자체는 completion_criteria로 분리합니다."},
		LastLessonRule:          "마지막 lesson은 역할 기반 task scenario와 다음 credential 또는 career step 직전까지 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 credential 취득, 직무 전환, 취업 지원은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"product menu만 훑기", "module 이름만 확인하기", "badge 이름만 보기"},
	},
	"digital_creation:professional_transition:cloud_lab_skill_path": {
		Name:                    "영어 cloud lab skill path형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "performance_prep"},
		StageRules:              []string{"리슨은 cloud product 목록이 아니라 역할 목표, 핵심 cloud module, hands-on lab 적용, badge 또는 certification 직전 점검으로 구성합니다.", "lab 하나는 독립 리슨이 아니라 역할 기반 task scenario를 연습하는 활동으로 둡니다."},
		LastLessonRule:          "마지막 lesson은 대표 cloud task scenario와 다음 badge 또는 certification 직전 준비를 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 skill badge 획득, certification 응시, 직무 전환은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"lab 하나만 실행하기", "badge 이름만 확인하기", "certification 응시 자체"},
	},
	"visual_art:artifact_creation:structured_drawing_foundation": {
		Name:                    "영어 구조화 드로잉 기초형",
		StepRoles:               []string{"setup_intro", "first_output", "core_pattern", "integration_practice", "artifact_finish"},
		StageRules:              []string{"리슨은 연필 종류나 선 하나를 따로 떼지 말고 도구와 첫 mark, 첫 sketch/output, contour·shading·perspective 핵심 패턴, 작은 작품 완성으로 이어져야 합니다.", "초보 드로잉은 빠른 첫 결과물과 반복 가능한 관찰·표현 패턴을 함께 보여야 합니다."},
		LastLessonRule:          "마지막 lesson은 contour, shading, perspective 중 핵심 패턴을 적용한 작은 드로잉 작품을 완성하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"작품 공개, 포트폴리오 게시, 장기 sketch routine은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"연필 종류만 보기", "선 하나만 긋기", "도구 이름만 외우기"},
	},
	"digital_creation:artifact_creation:creative_tool_beginner_output": {
		Name:                    "영어 creative tool beginner output형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "artifact_finish", "publish_prep"},
		StageRules:              []string{"리슨은 메뉴 위치나 효과 하나를 독립시키지 말고 도구·기초 개념, 핵심 technique 반복, 예제 output 적용, 결과물 마감, 공개·포트폴리오 직전 준비로 이어져야 합니다.", "Photoshop, Illustrator, video, web 같은 tool course는 기능 이름보다 beginner output 완성을 기준으로 경계를 잡습니다."},
		LastLessonRule:          "마지막 lesson은 첫 creative output을 정리하고 공개나 포트폴리오 직전까지 준비하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 공개, 판매, 수주, 플랫폼 업로드는 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"메뉴 위치만 보기", "효과 하나만 적용하기", "단축키만 외우기"},
	},
	"digital_creation:technical_skill:ai_tool_productivity_workflow": {
		Name:                    "AI 도구 생산성 워크플로우형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "routine_plan"},
		StageRules:              []string{"리슨은 프롬프트 예시 모음이 아니라 반복 업무 선정, 입력 자료 정리, AI 초안 생성, 검토·수정, 개인 워크플로우 정착으로 이어져야 합니다.", "생산성 목표에서는 자동화 자체보다 결과 검증, 개인정보 주의, 반복 가능한 작업 절차를 함께 다룹니다."},
		LastLessonRule:          "마지막 lesson은 문서 요약, 메일 초안, 표 정리 같은 반복 업무 하나에 AI 도구 워크플로우를 적용하고 다음 사용 기준을 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"팀 도입, 유료 도구 구독, 업무 성과 평가는 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"프롬프트 목록만 보기", "도구 가입만 하기", "AI 결과를 검토 없이 복사하기"},
	},
	"digital_creation:technical_skill:computational_music_analysis_project": {
		Name:                    "영어 computational music analysis project형",
		StepRoles:               []string{"setup_intro", "core_pattern", "first_output", "integration_practice", "analysis_project", "presentation_prep"},
		StageRules:              []string{"리슨은 lecture나 problem set 번호를 복제하지 말고 Python/music21 setup, symbolic representation, 첫 분석 output, corpus/statistics 통합, 작은 analysis project로 이어져야 합니다.", "환경 세팅과 score 읽기는 독립 리슨보다 분석 output을 만들기 위한 첫 관문 안에 둡니다."},
		LastLessonRule:          "마지막 lesson은 작은 computational music analysis 결과를 발표 직전까지 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"공식 research project 제출, 수강 완료, 학점 취득은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"Python 설치만 하기", "lecture 하나 보기", "problem set 번호 복제"},
	},
	"digital_creation:artifact_creation:adobe_creative_learning_path": {
		Name:                    "영어 Adobe creative learning path형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "artifact_finish", "publish_prep"},
		StageRules:              []string{"리슨은 앱별 tutorial을 그대로 나열하지 말고 작업 유형 선택, 핵심 기능 패턴, 예제 output 적용, 결과물 마감, 공개·포트폴리오 준비로 압축합니다.", "효과 하나나 badge 이름은 독립 리슨이 아니라 creative output을 만드는 활동 안에 흡수합니다."},
		LastLessonRule:          "마지막 lesson은 첫 creative output을 공개나 포트폴리오 직전까지 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 badge 획득, 유료 구독, 포트폴리오 공개, 수익화는 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"tutorial 하나만 보기", "효과 하나만 적용하기", "badge 이름만 확인하기"},
	},
	"digital_creation:artifact_creation:template_design_quick_output": {
		Name:                    "영어 template design quick output형",
		StepRoles:               []string{"setup_intro", "first_output", "core_pattern", "artifact_finish"},
		StageRules:              []string{"리슨은 템플릿 탐색이나 버튼 위치 설명보다 편집기 입문, 첫 템플릿 output, 디자인 요소 조정, 공유 가능한 결과물 완성으로 이어져야 합니다.", "템플릿 기반 목표는 빠른 첫 결과물과 반복 가능한 디자인 수정 패턴이 드러나야 합니다."},
		LastLessonRule:          "마지막 lesson은 공유 가능한 디자인 산출물을 완성하고 형식과 전달 목적을 점검하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 브랜드 운영, 캠페인 게시, 유료 asset 구매는 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"템플릿 하나 고르기", "폰트 하나 바꾸기", "버튼 위치 익히기"},
	},
	"visual_art:artifact_creation:sequential_creative_class_path": {
		Name:                    "영어 sequential creative class path형",
		StepRoles:               []string{"setup_intro", "first_output", "core_pattern", "integration_practice", "artifact_finish", "publish_prep"},
		StageRules:              []string{"리슨은 class 하나씩 시청하는 순서가 아니라 창작 목표 선택, 첫 project, 기법 class 반복, 작품 묶음 통합, 공개·사업화 준비로 압축합니다.", "gallery나 project 공유는 lesson 경계가 아니라 결과물 점검과 completion 기준으로 둡니다."},
		LastLessonRule:          "마지막 lesson은 공개하거나 포트폴리오에 넣을 수 있는 작품 묶음을 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 class 수료, certificate, 유료 구독, 판매 시작은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"class 하나 시청하기", "certificate만 받기", "project gallery만 둘러보기"},
	},
	"digital_creation:artifact_creation:animation_fundamentals_shot_progression": {
		Name:                    "영어 animation fundamentals shot progression형",
		StepRoles:               []string{"setup_intro", "first_output", "core_pattern", "integration_practice", "artifact_finish"},
		StageRules:              []string{"리슨은 Blender 파일 다운로드나 rig 이름 암기가 아니라 animation workflow, 첫 bouncing output, motion pattern, body mechanics, 짧은 character shot으로 이어져야 합니다.", "동작 원리는 독립 이론보다 실제 shot 품질을 올리는 관문 안에서 다룹니다."},
		LastLessonRule:          "마지막 lesson은 짧은 character animation shot을 완성하고 timing과 motion quality를 점검하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"작품 공개, showreel 등록, 유료 asset 구매는 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"파일 다운로드", "동작 하나만 보기", "rig 이름만 익히기"},
	},
	"digital_creation:artifact_creation:interactive_music_production_foundation": {
		Name:                    "영어 interactive music production foundation형",
		StepRoles:               []string{"setup_intro", "first_output", "core_pattern", "integration_practice", "artifact_finish"},
		StageRules:              []string{"리슨은 scale 이름이나 drum pattern 하나가 아니라 음악 제작 인터페이스, 첫 beat/loop, rhythm·melody·harmony 패턴, song section 통합, 짧은 track sketch 완성으로 이어져야 합니다.", "브라우저 interactive 활동은 각 제작 관문 안의 연습 활동으로 둡니다."},
		LastLessonRule:          "마지막 lesson은 짧은 track sketch를 완성하고 구조와 반복 가능성을 점검하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 음원 공개, 배포, 유료 DAW 구매는 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"드럼 패턴 하나", "코드 하나", "scale 이름만 보기"},
	},
	"digital_creation:artifact_creation:music_production_full_pipeline": {
		Name:                    "영어 music production full pipeline형",
		StepRoles:               []string{"setup_intro", "core_pattern", "first_output", "integration_practice", "artifact_finish", "publish_prep"},
		StageRules:              []string{"리슨은 level이나 영상 목록을 복제하지 말고 DAW/audio setup, sequencer·MIDI 핵심 패턴, 첫 beat/loop, composition/arrangement 통합, mix/master 직전 track 완성, export·공개 준비로 압축합니다.", "sound design, audio processing, arrangement, mixing은 최종 track 품질을 올리는 제작 관문으로 묶습니다."},
		LastLessonRule:          "마지막 lesson은 track을 export하거나 공개하기 직전까지 mix/master 상태와 구조를 점검하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 음원 공개, 수익화, certificate 취득, 유료 tutoring은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"level 하나만 보기", "plugin 이름만 외우기", "export 버튼만 누르기"},
	},
	"visual_art:artifact_creation:photography_fundamentals_project": {
		Name:                    "영어 photography fundamentals project형",
		StepRoles:               []string{"setup_intro", "core_pattern", "first_output", "integration_practice", "artifact_finish"},
		StageRules:              []string{"리슨은 ISO나 aperture 정의만 다루지 말고 카메라/스마트폰 조작 입문, exposure/composition 핵심 패턴, 첫 촬영 output, lighting/focus/portrait 응용, 작은 photo project 완성으로 이어져야 합니다.", "simulator, quiz, glossary는 독립 리슨이 아니라 촬영 과제 안의 확인 활동으로 둡니다.", "일상 사진이나 인물 사진 목표는 구도, 빛, 초점, 배경 정리, 포즈 유도 같은 촬영 행동으로 연결합니다."},
		LastLessonRule:          "마지막 lesson은 exposure, composition, lighting/focus를 적용해 일상 또는 인물 중심의 작은 photo project를 완성하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"장기 portfolio 운영, 유료 장비 구매, 공개 전시는 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"ISO 정의만 보기", "quiz 하나만 풀기", "camera mode 하나만 누르기"},
	},
	"writing_storytelling:presentation_publish:critical_reading_to_writing_draft": {
		Name:                    "영어 critical reading-to-writing draft형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "first_output", "publish_prep"},
		StageRules:              []string{"리슨은 작품 하나를 읽는 데서 끝나지 않고 critical reading 입문, reading-as-writer 핵심 패턴, 텍스트 분석 적용, 장르별 writing draft, 수정·공개 직전 준비로 이어져야 합니다.", "읽기 분석은 반드시 learner의 writing draft를 개선하는 활동으로 연결합니다."},
		LastLessonRule:          "마지막 lesson은 장르별 draft를 수정해 공개나 제출 직전 상태로 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"statement of participation, 실제 출판, 공식 제출은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"작품 하나만 읽기", "용어 정의만 보기", "statement of participation 받기"},
	},
	"visual_art:artifact_creation:photography_studio_project": {
		Name:                    "영어 photography studio project형",
		StepRoles:               []string{"setup_intro", "core_pattern", "first_output", "integration_practice", "artifact_finish", "publish_prep"},
		StageRules:              []string{"리슨은 orientation이나 review 참석을 독립시키지 말고 camera/media 입문, analog/digital 핵심 기술, 첫 image production, critique 기반 통합 작업, term project 완성, exhibition 직전 준비로 구성합니다.", "critique는 별도 목표가 아니라 작품 개선을 위한 반복 활동입니다."},
		LastLessonRule:          "마지막 lesson은 photography term project를 완성하고 exhibition 또는 presentation 직전까지 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 exhibition, 공식 critique 통과, course completion은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"review 참석만 하기", "darkroom orientation만 보기", "artist presentation만 준비하기"},
	},
	"digital_creation:certification_assessment:cloud_foundation_certification": {
		Name:                    "클라우드 입문 자격형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "performance_prep"},
		StageRules:              []string{"리슨은 콘솔 조작보다 핵심 개념과 서비스 범주 이해에 초점을 둡니다.", "입문형은 대표 서비스 역할 구분과 사례 판단 흐름이 드러나야 합니다."},
		LastLessonRule:          "마지막 lesson은 시험 직전까지 대표 서비스와 문제 유형 흐름을 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 시험 응시와 자격 취득은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"서비스 이름만 나열하기", "콘솔 메뉴만 익히기"},
	},
	"digital_creation:certification_assessment:cloud_operator_certification": {
		Name:                    "클라우드 실무 자격형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "performance_prep"},
		StageRules:              []string{"리슨은 개념 암기보다 운영·배포·보안·네트워크 시나리오 판단에 초점을 둡니다.", "대표 아키텍처와 장애 대응, 권한, 네트워크 연결 흐름이 포함되어야 합니다."},
		LastLessonRule:          "마지막 lesson은 시험 직전까지 시나리오 문제풀이 흐름을 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 시험 응시와 자격 취득은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"서비스 목록만 보기", "용어 정의만 외우기"},
	},
	"digital_creation:certification_assessment:software_engineering_certification": {
		Name:                    "소프트웨어 기사형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "performance_prep"},
		StageRules:              []string{"리슨은 과목별 핵심 개념과 대표 문제 유형을 실제 풀이 흐름으로 연결하는 데 초점을 둡니다.", "개념 정리만으로 끝내지 말고 기출형 문제풀이 단계가 포함되어야 합니다."},
		LastLessonRule:          "마지막 lesson은 시험 직전까지 핵심 과목과 문제풀이 흐름을 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 시험 응시와 자격 취득은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"용어 정의만 보기", "이론 목록만 암기하기"},
	},
	"digital_creation:certification_assessment:office_tool_practical_certification": {
		Name:                    "오피스 실기 자격형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "performance_prep"},
		StageRules:              []string{"리슨은 메뉴 소개보다 실제 작업형 문제를 시간 안에 수행하는 흐름에 초점을 둡니다.", "함수, 서식, 데이터 처리, 출력 흐름이 대표 작업 과제로 연결되어야 합니다."},
		LastLessonRule:          "마지막 lesson은 실기 시험 직전까지 작업 순서와 시간 배분을 점검하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 시험 응시와 자격 취득은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"메뉴 위치만 보기", "기능 이름만 암기하기"},
	},
	"digital_creation:certification_assessment:korean_design_tool_practical_certification": {
		Name:                    "한국 디자인 도구 실기 자격형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "artifact_finish", "performance_prep"},
		StageRules:              []string{"리슨은 포토샵/그래픽 도구 메뉴 암기보다 시험 구조, 핵심 패널과 레이어, 유형별 작업형 문제, 통합 산출물, 제한시간 연습으로 이어져야 합니다.", "전단지, 사진 보정, 웹/모바일 디자인 같은 산출물은 기능 설명 뒤가 아니라 실제 작업형 문제 안에서 다룹니다."},
		LastLessonRule:          "마지막 lesson은 실기 시험 직전까지 대표 유형을 제한시간 안에 수행하는 모의고사 점검 단계여야 합니다.",
		CompletionCriteriaRules: []string{"KPC 계정 생성, 원서접수, 실제 시험 응시, 결과 확인, 자격증 신청은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"포토샵 화면만 둘러보기", "메뉴 이름만 외우기", "원서접수만 하기"},
	},
	"digital_creation:professional_transition:korean_ncs_web_publisher_training": {
		Name:                    "한국 NCS 웹퍼블리셔 직업훈련형",
		StepRoles:               []string{"setup_intro", "structure_plan", "core_pattern", "integration_practice", "artifact_finish", "performance_prep"},
		StageRules:              []string{"리슨은 훈련기간이나 지원제도 설명이 아니라 NCS 직무 이해, UI/UX 구조 설계, HTML/CSS/JS 핵심 구현, 반응형 프로젝트 통합, 포트폴리오 정리로 이어져야 합니다.", "취업지원 요소는 이력서·자소서 자체보다 포트폴리오와 직무역량을 설명 가능한 상태로 만드는 데 연결합니다."},
		LastLessonRule:          "마지막 lesson은 웹퍼블리셔/프론트엔드 지원 직전까지 포트폴리오와 지원 자료를 점검하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"국민내일배움카드 신청, 훈련비 지원, 출석, 상담, 실제 취업은 completion_criteria 또는 후속 목표로 분리합니다."},
		AtomicDisallowExamples:  []string{"훈련비 확인만 하기", "출석하기", "HTML 태그 이름만 외우기"},
	},
	"digital_creation:artifact_creation:korean_content_creation_pipeline": {
		Name:                    "한국 콘텐츠 제작 파이프라인형",
		StepRoles:               []string{"setup_intro", "core_pattern", "first_output", "integration_practice", "publish_prep"},
		StageRules:              []string{"리슨은 방송영상, 게임, 만화·애니메이션, 음악·공연 같은 장르 선택 뒤 제작 핵심 패턴, 첫 결과물, 통합 작업, 공개·포트폴리오 준비로 이어져야 합니다.", "업계 취업이나 실제 배포보다 제작 흐름과 결과물 정리에 초점을 둡니다."},
		LastLessonRule:          "마지막 lesson은 콘텐츠 결과물을 공개 또는 포트폴리오 직전까지 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"콘텐츠 업계 취업, 실제 플랫폼 배포, 공모전 수상은 completion_criteria 또는 후속 목표로 분리합니다."},
		AtomicDisallowExamples:  []string{"장르 목록만 보기", "툴 이름만 외우기", "취업 성공 자체"},
	},
	"writing_storytelling:presentation_publish:university_studio": {
		Name:                    "대학 studio/workshop형",
		StepRoles:               []string{"setup_intro", "first_output", "core_pattern", "integration_practice", "artifact_finish"},
		StageRules:              []string{"리슨은 도구나 이론 설명만 길게 두지 말고 초반에 작은 초안이나 첫 결과물이 빠르게 나오도록 구성합니다.", "중반 이후에는 기법 반복, 피드백 반영, 수정 주기가 보이고 마지막은 제출 가능한 작업물 직전 수준까지 올라가야 합니다."},
		LastLessonRule:          "마지막 lesson은 발표나 제출 직전까지 작업물을 다듬고 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 발표, 공식 제출, 수강 완료는 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"도구 설명만 보기", "개념 정의만 읽기", "형식 규정만 보기"},
	},
	"visual_art:artifact_creation:university_studio": {
		Name:                    "대학 studio/workshop형",
		StepRoles:               []string{"setup_intro", "first_output", "core_pattern", "integration_practice", "artifact_finish"},
		StageRules:              []string{"리슨은 도구나 이론 설명만 길게 두지 말고 초반에 작은 초안이나 첫 결과물이 빠르게 나오도록 구성합니다.", "중반 이후에는 기법 반복, 피드백 반영, 수정 주기가 보이고 마지막은 제출 가능한 작업물 직전 수준까지 올라가야 합니다."},
		LastLessonRule:          "마지막 lesson은 발표나 제출 직전까지 작업물을 다듬고 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 발표, 공식 제출, 수강 완료는 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"도구 설명만 보기", "개념 정의만 읽기", "형식 규정만 보기"},
	},
	"digital_creation:artifact_creation:university_studio": {
		Name:                    "대학 studio/workshop형",
		StepRoles:               []string{"setup_intro", "first_output", "core_pattern", "integration_practice", "artifact_finish"},
		StageRules:              []string{"리슨은 도구나 이론 설명만 길게 두지 말고 초반에 작은 초안이나 첫 결과물이 빠르게 나오도록 구성합니다.", "중반 이후에는 기법 반복, 피드백 반영, 수정 주기가 보이고 마지막은 제출 가능한 작업물 직전 수준까지 올라가야 합니다."},
		LastLessonRule:          "마지막 lesson은 발표나 제출 직전까지 작업물을 다듬고 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 발표, 공식 제출, 수강 완료는 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"도구 설명만 보기", "개념 정의만 읽기", "형식 규정만 보기"},
	},
}
