package curriculum

var goalSubpatternSpecsCraftMakerCooking = map[string]goalSubpatternSpec{
	"craft_making:teaching_instruction:craft_teach_youtube": {
		Name:                    "공예 유튜브 강의형",
		StepRoles:               []string{"first_output", "core_pattern", "structure_plan", "artifact_finish", "teaching_prep"},
		StageRules:              []string{"리슨은 기초 설명보다 실제 결과물 완성과 제작 흐름 설명 준비에 초점을 둡니다.", "도안 표기, 재료 선택, 반복 패턴은 독립 리슨이 아니라 작품 구조를 설명하는 단계 안에 흡수되어야 합니다."},
		LastLessonRule:          "마지막 lesson은 제작 과정을 설명하고 시연할 준비를 마치는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 유튜브 업로드와 강의 개시는 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"재료 소개", "도안 표기만 보기", "기본 포인트 하나"},
	},
	"craft_making:artifact_creation:woodworking_small_project": {
		Name:                    "목공예 소품 제작형",
		StepRoles:               []string{"setup_intro", "structure_plan", "core_pattern", "artifact_finish"},
		StageRules:              []string{"리슨은 공구 이름이나 목재 종류 소개만으로 분리하지 말고 목재 선택, 치수 계획, 재단, 샌딩, 조립, 마감 흐름으로 이어져야 합니다.", "초보 목공예 목표에서는 도마, 작은 선반, 받침대처럼 실패 비용이 낮고 완성 형태가 분명한 소품을 중심으로 구성합니다."},
		LastLessonRule:          "마지막 lesson은 사용할 수 있는 목공 소품 한 점을 완성하고 표면, 모서리, 마감 상태를 점검하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"완성품 사용 테스트와 제작 기록은 completion_criteria로 분리할 수 있습니다.", "판매, 주문 제작, 공방 수업 운영은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"공구 이름만 외우기", "목재 종류만 보기", "사포질만 하기"},
	},
	"craft_making:artifact_creation:knitting_basic_wearable": {
		Name:                    "대바늘 착용 소품 제작형",
		StepRoles:               []string{"setup_intro", "first_output", "core_pattern", "integration_practice", "artifact_finish"},
		StageRules:              []string{"리슨은 실과 바늘 소개만으로 분리하지 말고 코 잡기, 겉뜨기와 안뜨기, 단수와 폭 유지, 반복 무늬, 마감 흐름으로 이어져야 합니다.", "목도리 같은 착용 소품 목표에서는 길이와 폭을 일정하게 유지하며 끝까지 완성하는 반복 관문이 드러나야 합니다."},
		LastLessonRule:          "마지막 lesson은 실제 착용할 수 있는 목도리나 니트 소품 한 점을 마감하고 실 정리까지 끝내는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"완성품 착용 사진이나 제작 기록은 completion_criteria로 분리할 수 있습니다.", "판매나 선물 전달은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"실 종류만 보기", "코 하나만 뜨기", "무늬 사진만 모으기"},
	},
	"craft_making:artifact_creation:crochet_small_doll_project": {
		Name:                    "코바늘 작은 인형 제작형",
		StepRoles:               []string{"setup_intro", "first_output", "core_pattern", "integration_practice", "artifact_finish"},
		StageRules:              []string{"리슨은 코바늘 기호나 뜨기법 이름만 나열하지 말고 원형뜨기, 짧은뜨기, 증감, 솜 넣기, 부품 연결, 얼굴·마감 흐름으로 이어져야 합니다.", "아미구루미나 작은 인형 목표에서는 몸통과 부품을 따로 만든 뒤 연결하고 형태를 잡는 단계가 필요합니다."},
		LastLessonRule:          "마지막 lesson은 작은 코바늘 인형 한 점을 완성하고 형태, 연결, 마감 상태를 점검하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"완성 인형 촬영이나 제작 기록은 completion_criteria로 분리할 수 있습니다.", "판매나 도안 배포는 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"기호만 외우기", "원형 한 단만 뜨기", "실 색만 고르기"},
	},
	"craft_making:artifact_creation:pottery_handbuilding_cup_project": {
		Name:                    "도자기 핸드빌딩 컵 제작형",
		StepRoles:               []string{"setup_intro", "first_output", "core_pattern", "integration_practice", "artifact_finish"},
		StageRules:              []string{"리슨은 흙 종류나 도구 소개만으로 분리하지 말고 흙 준비, 기본 성형, 컵 형태 잡기, 손잡이 접합, 표면 정리, 유약·소성 준비 흐름으로 이어져야 합니다.", "머그컵 목표에서는 물을 담을 수 있는 형태와 손잡이 접합 안정성을 함께 점검하는 단계가 필요합니다."},
		LastLessonRule:          "마지막 lesson은 머그컵 한 점을 완성하고 형태, 손잡이 접합, 표면, 유약 준비 상태를 점검하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 소성 완료, 공방 수업 참여, 완성품 사용 테스트는 completion_criteria로 분리할 수 있습니다.", "판매나 주문 제작은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"흙 종류만 보기", "손잡이만 붙이기", "유약 색만 고르기"},
	},
	"craft_making:artifact_creation:candle_soap_resin_project": {
		Name:                    "캔들·비누·레진 소품 제작형",
		StepRoles:               []string{"setup_intro", "first_output", "core_pattern", "integration_practice", "artifact_finish"},
		StageRules:              []string{"리슨은 재료 소개만으로 분리하지 말고 안전한 계량, 몰드 준비, 색·향 조합, 굳힘·탈형, 마감 점검 흐름으로 이어져야 합니다.", "초보 소품 목표에서는 캔들·비누·레진 중 하나의 작은 결과물을 완성하되 온도, 환기, 피부 접촉 안전을 함께 다룹니다."},
		LastLessonRule:          "마지막 lesson은 사용할 수 있는 캔들·비누·레진 소품 한 점을 완성하고 표면, 향, 경화, 포장 상태를 점검하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"대량 제작, 판매, 선물 전달, 화장품·공산품 인증은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"향료만 고르기", "몰드 구경만 하기", "재료 구매 목록만 보기"},
	},
	"craft_making:artifact_creation:leathercraft_basic_accessory": {
		Name:                    "가죽공예 기본 소품 제작형",
		StepRoles:               []string{"setup_intro", "first_output", "core_pattern", "artifact_finish"},
		StageRules:              []string{"리슨은 가죽 종류와 도구 소개만으로 분리하지 말고 작은 소품 제작 흐름 안에 재단, 타공, 바느질, 엣지 마감을 연결해야 합니다.", "초보 목표에서는 실패 비용이 낮은 키홀더·카드 케이스·동전지갑 같은 작은 결과물부터 시작합니다."},
		LastLessonRule:          "마지막 lesson은 직접 만든 가죽 소품 한 점을 완성하고 마감 상태를 점검하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"완성품 사진 또는 제작 기록 제출은 completion_criteria로 분리할 수 있습니다.", "실제 판매나 수강 자격 취득은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"가죽 종류만 보기", "도구 이름만 외우기", "바느질 한 땀만 연습"},
	},
	"craft_making:artifact_creation:leathercraft_wallet_project": {
		Name:                    "가죽공예 지갑 프로젝트형",
		StepRoles:               []string{"setup_intro", "structure_plan", "core_pattern", "artifact_finish"},
		StageRules:              []string{"리슨은 지갑 구조와 패턴 이해, 외피·내피 재단, 타공과 새들스티치, 엣지 마감 순서가 드러나야 합니다.", "카드 수납, 접힘, 두께, 바느질 균일도처럼 실제 사용성을 점검하는 단계가 포함되어야 합니다."},
		LastLessonRule:          "마지막 lesson은 사용할 수 있는 지갑 한 점을 완성하고 수납과 마감 품질을 점검하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 사용할 수 있는 지갑 완성은 completion_criteria로 분리할 수 있습니다.", "판매나 선물 전달은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"템플릿만 내려받기", "재단선만 보기", "엣지코트 설명만 보기"},
	},
	"craft_making:artifact_creation:leathercraft_dimensional_bag": {
		Name:                    "가죽공예 입체 가방 제작형",
		StepRoles:               []string{"setup_intro", "structure_plan", "core_pattern", "integration_practice", "artifact_finish"},
		StageRules:              []string{"리슨은 평면 소품 기술 점검 뒤 안감, 거싯, 포켓, 여밈, 하드웨어, 다층 조립 순서를 다룹니다.", "입체 구조는 조립 순서 실수가 치명적이므로 부품 배치와 조립 순서를 독립된 학습 관문으로 둡니다."},
		LastLessonRule:          "마지막 lesson은 입체 구조가 유지되는 가죽 가방이나 파우치 한 점을 완성하고 구조 안정성을 점검하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"완성품 사용 테스트와 개선 기록은 completion_criteria로 분리할 수 있습니다.", "판매와 의뢰 수주는 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"하드웨어 소개만 보기", "패턴 용어만 외우기", "가방 사진만 모으기"},
	},
	"cooking_baking:habit_lifestyle:food_preservation_safety_path": {
		Name:                    "영어 food preservation safety형",
		StepRoles:               []string{"safety_intro", "core_pattern", "procedure_plan", "integration_practice", "artifact_finish"},
		StageRules:              []string{"리슨은 recipe 나열보다 high acid food, boiling water bath, steam canning, acidifying, research-tested recipe 같은 안전 기준을 절차 설계로 연결해야 합니다.", "장비 구매나 대량 보존은 독립 리슨이 아니라 준비 조건 또는 completion 기준으로 둡니다."},
		LastLessonRule:          "마지막 lesson은 안전 기준을 적용한 작은 preservation 결과물을 점검하거나 절차를 완성하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 대량 보존, 유료 수강 등록, 장비 구매는 completion_criteria 또는 후속 목표로 분리합니다."},
		AtomicDisallowExamples:  []string{"장비 목록만 보기", "산도 정의만 보기", "recipe 하나 읽기"},
	},
	"maker_technical_hobby:artifact_creation:arduino_sensor_project": {
		Name:                    "아두이노 센서 프로젝트형",
		StepRoles:               []string{"setup_intro", "first_output", "core_pattern", "integration_practice", "artifact_finish"},
		StageRules:              []string{"리슨은 부품 이름이나 보드 소개만으로 분리하지 말고 보드 연결, LED 첫 출력, 센서 입력 읽기, 코드와 회로 통합, 작은 작동 장치 완성으로 이어져야 합니다.", "초보 전자공작 목표에서는 고급 회로 이론보다 배선 실수 점검, 시리얼 모니터 확인, 센서값을 동작으로 연결하는 흐름을 우선합니다."},
		LastLessonRule:          "마지막 lesson은 센서 입력으로 LED·서보·소리 같은 출력을 제어하는 작은 아두이노 장치를 완성하고 배선과 코드 상태를 점검하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"키트 구매, 대회 출품, 제품화, 워크숍 운영은 completion_criteria 또는 후속 목표로 분리합니다."},
		AtomicDisallowExamples:  []string{"부품 목록만 보기", "보드 구매만 하기", "LED 하나 켜고 끝내기"},
	},
	"maker_technical_hobby:artifact_creation:design_thinking_problem_framing_path": {
		Name:                    "영어 design thinking problem framing형",
		StepRoles:               []string{"empathy_setup", "problem_define", "ideation_practice", "prototype_build", "test_reflection"},
		StageRules:              []string{"리슨은 method card를 읽는 순서가 아니라 empathy, define, ideate, prototype, test의 human-centered design loop로 구성합니다.", "brainstorm이나 interview는 독립 리슨보다 문제 정의와 prototype 검증 흐름 안에 배치합니다."},
		LastLessonRule:          "마지막 lesson은 prototype test 결과와 배운 점을 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 제품 출시, 대외 발표, 조직 도입은 completion_criteria 또는 후속 목표로 분리합니다."},
		AtomicDisallowExamples:  []string{"카드 하나 읽기", "brainstorm만 하기", "solution만 나열하기"},
	},
	"maker_technical_hobby:artifact_creation:no_build_prototype_test": {
		Name:                    "영어 no-build prototype test형",
		StepRoles:               []string{"question_setup", "prototype_plan", "scrappy_build", "test_session", "learning_reflection"},
		StageRules:              []string{"리슨은 최종 제품 구현이 아니라 검증 질문, 간단한 장면/재료 구성, 사용자 반응 관찰, 배운 점 정리로 이어져야 합니다.", "cardboard, paper, tape, furniture 같은 재료는 prototype test를 가능하게 하는 수단으로 다룹니다."},
		LastLessonRule:          "마지막 lesson은 no-build prototype test에서 배운 점과 다음 iteration 방향을 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 배포, 완성품 제작, 유료 재료 구매는 completion_criteria 또는 후속 목표로 분리합니다."},
		AtomicDisallowExamples:  []string{"재료 구매만 하기", "최종 제품 만들기", "아이디어만 말하기"},
	},
	"maker_technical_hobby:artifact_creation:maker_project_class": {
		Name:                    "영어 maker project class형",
		StepRoles:               []string{"setup_intro", "structure_plan", "core_pattern", "artifact_finish", "teaching_prep"},
		StageRules:              []string{"리슨은 재료 목록이나 사진 업로드가 아니라 프로젝트 주제와 재료 파악, 제작 구조 계획, 핵심 제작 과정, 결과물 완성, 설명·수업 활용 준비로 이어져야 합니다.", "제작 단계 하나는 독립 리슨보다 작동하는 결과물을 만드는 관문 안에 둡니다."},
		LastLessonRule:          "마지막 lesson은 maker 결과물을 완성하고 제작 과정을 설명할 수 있게 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 수업 운영, 공개 게시, 대회 제출, 판매는 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"재료 목록만 보기", "단계 하나만 수행하기", "사진만 업로드하기"},
	},
	"craft_making:artifact_creation:sewing_project_foundation": {
		Name:                    "영어 sewing project foundation형",
		StepRoles:               []string{"setup_intro", "core_pattern", "structure_plan", "integration_practice", "artifact_finish"},
		StageRules:              []string{"리슨은 재봉틀 부품이나 실 종류를 따로 떼지 말고 도구·재봉틀 입문, 원단 선택과 재단, 직선 박기, seam/hem 통합 연습, 초급 봉제 결과물 마감으로 이어져야 합니다.", "초보 sewing은 개념 암기보다 에코백, 파우치, 쿠션커버처럼 작은 결과물에 필요한 손기술과 순서가 함께 보여야 합니다."},
		LastLessonRule:          "마지막 lesson은 에코백이나 초급 봉제 결과물을 완성하고 stitch, seam, hem, 마감 상태를 점검하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"certificate 취득, 의류 판매, tailor 수준 숙련은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"재봉틀 부품 이름만 보기", "실 종류만 외우기", "hem 하나만 연습하기"},
	},
	"maker_technical_hobby:artifact_creation:cardboard_circuit_invention_path": {
		Name:                    "영어 cardboard circuit invention path형",
		StepRoles:               []string{"setup_intro", "structure_plan", "core_pattern", "integration_practice", "artifact_finish", "teaching_prep"},
		StageRules:              []string{"리슨은 부품 목록이나 cardboard cutting만 나열하지 말고 재료와 kit 파악, invention idea와 design plan, circuit/robotics 핵심 연결, prototype iteration, 작동 결과물 완성, 제작 과정 설명 준비로 이어져야 합니다.", "실패와 반복이 핵심이므로 회로 연결과 prototype 수정이 같은 흐름 안에 있어야 합니다."},
		LastLessonRule:          "마지막 lesson은 작동하는 cardboard circuit 결과물을 완성하고 제작 과정을 설명할 준비를 하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"kit 구매, 공식 수업 운영, 공개 게시, 대회 제출은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"부품 목록만 보기", "cardboard만 자르기", "센서 이름만 외우기"},
	},
	"cooking_baking:artifact_creation:korean_home_cooking_basics": {
		Name:                    "집밥 한식 기초형",
		StepRoles:               []string{"setup_intro", "structure_plan", "core_pattern", "integration_practice", "artifact_finish"},
		StageRules:              []string{"리슨은 재료 목록이나 레시피 수집만으로 분리하지 말고 주방 안전, 재료 손질, 국·찌개 간 맞추기, 밑반찬 조리, 한 끼 집밥 완성 흐름으로 이어져야 합니다.", "초보 집밥 목표에서는 자격증 실기보다 된장찌개, 계란말이, 밑반찬처럼 반복 가능한 생활요리 기본기를 우선합니다."},
		LastLessonRule:          "마지막 lesson은 먹을 수 있는 집밥 한 끼를 완성하고 간, 익힘, 위생, 정리 상태를 점검하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"한식조리기능사 시험, 식당 창업, 장기 식단 유지 성공은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"레시피 저장만 하기", "칼 이름만 외우기", "재료 구매만 하기"},
	},
	"cooking_baking:artifact_creation:cooking_basics_foundation": {
		Name:                    "영어 cooking basics foundation형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "artifact_finish"},
		StageRules:              []string{"리슨은 주방 안전과 위생, utensil/knife 핵심 패턴, stock/sauce/dough 통합 연습, herbs/spices 활용 초급 dish 완성으로 이어져야 합니다.", "도구 이름이나 향신료 목록은 독립 리슨이 아니라 실제 조리 수행 단계 안에 흡수합니다."},
		LastLessonRule:          "마지막 lesson은 안전한 조리 흐름으로 초급 dish를 완성하고 맛과 위생 기준을 점검하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"assessment, certificate, 직업 chef 전환은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"칼 이름만 외우기", "향신료 목록만 보기", "위생 규칙 하나만 읽기"},
	},
	"cooking_baking:habit_lifestyle:meal_prep_weekday_lunch": {
		Name:                    "주간 점심 밀프렙 루틴형",
		StepRoles:               []string{"setup_intro", "structure_plan", "core_pattern", "integration_practice", "routine_plan"},
		StageRules:              []string{"리슨은 레시피 목록보다 주간 점심 목표 설정, 장보기/재료 손질, 안전한 일괄 조리, 보관/재가열, 다음 주 반복 루틴으로 이어져야 합니다.", "건강식 목표에서는 영양 이론을 길게 분리하지 말고 실제 점심 구성과 보관 실천 안에 흡수합니다."},
		LastLessonRule:          "마지막 lesson은 한 주 점심 meal prep 결과를 점검하고 다음 주 반복 계획을 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"체중 감량, 전문 영양 상담, 장기 식단 유지 성공은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"레시피 수집만 하기", "칼질만 연습하기", "영양소 이론만 보기"},
	},
	"cooking_baking:artifact_creation:home_cafe_latte_foundation": {
		Name:                    "홈카페 라떼 기초형",
		StepRoles:               []string{"setup_intro", "first_output", "core_pattern", "integration_practice", "artifact_finish"},
		StageRules:              []string{"리슨은 원두나 장비 소개만으로 분리하지 말고 에스프레소 추출, 우유 스티밍, 우유 질감 만들기, 라떼 비율 조절, 반복 레시피 안정화로 이어져야 합니다.", "홈카페 목표에서는 카페 장비 수준보다 집에서 반복 가능한 도구와 맛의 일관성을 우선합니다."},
		LastLessonRule:          "마지막 lesson은 집에서 마실 수 있는 라떼 한 잔을 안정적으로 만들고 추출, 우유 질감, 맛 균형을 점검하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"라떼아트 고급 패턴, 카페 창업, 판매는 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"원두 종류만 보기", "장비 비교만 하기", "우유 데우기만 하기"},
	},
	"maker_technical_hobby:artifact_creation:design_lab_prototype_project": {
		Name:                    "영어 design lab prototype project형",
		StepRoles:               []string{"setup_intro", "structure_plan", "core_pattern", "integration_practice", "artifact_finish", "performance_prep"},
		StageRules:              []string{"리슨은 design packet이나 guest talk를 그대로 옮기지 말고 문제 맥락 파악, design process와 requirement plan, fabrication/prototyping 핵심 패턴, review 기반 iteration, prototype 완성, real-world 적용 직전 준비로 이어져야 합니다.", "community partner 맥락은 prototype 요구사항과 검증 기준을 세우는 활동으로 다룹니다."},
		LastLessonRule:          "마지막 lesson은 prototype을 완성하고 실제 적용이나 review 직전까지 기능과 맥락 적합성을 점검하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"field implementation, community partner deployment, 공식 project 발표는 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"design packet 하나만 읽기", "guest talk만 듣기", "partner 조사만 하기"},
	},
	"maker_technical_hobby:teaching_instruction:maker_workshop_demo": {
		Name:                    "메이커 워크숍 시연형",
		StepRoles:               []string{"setup_intro", "first_output", "core_pattern", "artifact_finish", "teaching_prep"},
		StageRules:              []string{"리슨은 부품 설명보다 작동하는 프로젝트 제작과 설명 가능한 시연 흐름 정리에 초점을 둡니다.", "회로/부품 설명은 독립 리슨이 아니라 프로젝트 제작 단계 안에 흡수되어야 합니다."},
		LastLessonRule:          "마지막 lesson은 워크숍이나 시연 직전까지 설명 흐름을 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 워크숍 진행과 튜토리얼 공개는 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"부품 소개만 보기", "회로 설명만 보기"},
	},
	"maker_technical_hobby:certification_assessment:drone_operator_basic_4class": {
		Name:                    "드론 4종 이론형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "performance_prep"},
		StageRules:              []string{"리슨은 비행 실습보다 법규·안전·기체 운용 기본 이해에 초점을 둡니다.", "이러닝형 시험인 만큼 안전 규정과 운용 기준을 실제 판단 흐름으로 연결해야 합니다."},
		LastLessonRule:          "마지막 lesson은 시험 직전까지 법규와 안전 판단 흐름을 점검하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 교육 이수와 자격 취득은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"기체 명칭만 외우기", "법 조항만 읽기"},
	},
	"maker_technical_hobby:certification_assessment:drone_operator_practical_1to3class": {
		Name:                    "드론 실기 자격형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "performance_prep"},
		StageRules:              []string{"리슨은 법규와 안전 기준 위에 실제 조작과 비행 절차를 연결하는 데 초점을 둡니다.", "실기 과제와 비행 절차가 자연스럽게 이어지는 단계가 포함되어야 합니다."},
		LastLessonRule:          "마지막 lesson은 실기 시험 직전까지 비행 절차와 조작 흐름을 점검하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 시험 응시와 자격 취득은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"기체 소개만 보기", "법규 설명만 보기"},
	},
	"maker_technical_hobby:certification_assessment:equipment_operation_practical_certification": {
		Name:                    "장비·작업 실기 자격형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "performance_prep"},
		StageRules:              []string{"리슨은 장비 소개보다 안전 점검, 기본 조작, 대표 작업 흐름, 시간 안에 수행하는 실기 과제에 초점을 둡니다.", "지게차·용접·정비처럼 작업형 종목은 대표 과제 완성 흐름이 반드시 포함되어야 합니다."},
		LastLessonRule:          "마지막 lesson은 실기 시험 직전까지 안전 점검과 작업 흐름을 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 시험 응시와 자격 취득은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"공구 소개만 보기", "장비 이름만 외우기"},
	},
	"maker_technical_hobby:certification_assessment:construction_engineering_certification": {
		Name:                    "건설 기사형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "performance_prep"},
		StageRules:              []string{"리슨은 과목 이름 나열보다 구조·시공·법규·적산 등 핵심 영역을 문제풀이 흐름으로 연결하는 데 초점을 둡니다.", "기사·산업기사형은 대표 계산과 판단 문제 풀이 단계가 포함되어야 합니다."},
		LastLessonRule:          "마지막 lesson은 시험 직전까지 핵심 과목과 계산·판단 문제 흐름을 점검하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 시험 응시와 자격 취득은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"법규 목록만 보기", "공식만 암기하기"},
	},
	"maker_technical_hobby:certification_assessment:electrical_engineering_certification": {
		Name:                    "전기 기사형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "performance_prep"},
		StageRules:              []string{"리슨은 전기 이론, 기기, 설비, 공사 흐름을 실제 문제풀이와 계산 흐름으로 연결하는 데 초점을 둡니다.", "단순 개념 설명보다 계산, 회로 해석, 설비 판단 흐름이 드러나야 합니다."},
		LastLessonRule:          "마지막 lesson은 시험 직전까지 계산과 과목별 문제풀이 흐름을 점검하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 시험 응시와 자격 취득은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"공식만 외우기", "기기 이름만 나열하기"},
	},
	"cooking_baking:teaching_instruction:baking_class_demo": {
		Name:                    "베이킹 클래스 시연형",
		StepRoles:               []string{"setup_intro", "core_pattern", "artifact_finish", "teaching_prep"},
		StageRules:              []string{"리슨은 재료 소개보다 대표 메뉴 완성과 설명 가능한 레시피 흐름 정리에 초점을 둡니다.", "재료와 도구 설명은 독립 리슨이 아니라 결과물 제작 단계 안에 흡수되어야 합니다."},
		LastLessonRule:          "마지막 lesson은 레시피와 시연 흐름을 설명할 준비를 마친 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 클래스 오픈과 강의 공개는 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"재료 소개만 보기", "도구 소개만 보기"},
	},
	"cooking_baking:certification_assessment:baking_written_practical_certification": {
		Name:                    "제과·제빵 자격형",
		StepRoles:               []string{"setup_intro", "core_pattern", "artifact_finish", "performance_prep"},
		StageRules:              []string{"리슨은 재료 소개보다 공정 순서, 반죽·배합 기본기, 대표 과제 완성 흐름에 초점을 둡니다.", "실기 종목은 시간 안에 결과물을 완성하는 흐름이 드러나야 합니다."},
		LastLessonRule:          "마지막 lesson은 실기 시험 직전까지 작업 순서와 시간 배분을 점검하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 시험 응시와 자격 취득은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"재료 소개만 보기", "도구 이름만 외우기"},
	},
	"cooking_baking:certification_assessment:korean_cooking_practical_certification": {
		Name:                    "한식 조리 실기 자격형",
		StepRoles:               []string{"setup_intro", "core_pattern", "artifact_finish", "performance_prep"},
		StageRules:              []string{"리슨은 위생과 기본 손질을 바탕으로 대표 조리 과제 완성 흐름에 초점을 둡니다.", "칼질, 전처리, 조리 순서, 플레이팅이 과제 흐름 안에 자연스럽게 포함되어야 합니다."},
		LastLessonRule:          "마지막 lesson은 실기 시험 직전까지 조리 순서와 시간 배분을 점검하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 시험 응시와 자격 취득은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"재료 소개만 보기", "위생 규정만 읽기"},
	},
	"craft_making:certification_assessment:beauty_service_practical_certification": {
		Name:                    "미용 서비스 실기 자격형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "performance_prep"},
		StageRules:              []string{"리슨은 이론 설명보다 위생 기준, 도구 준비, 대표 작업 패턴, 공개과제 수행 흐름에 초점을 둡니다.", "피부·네일·헤어는 반복 작업 패턴과 순서가 자연스럽게 이어져야 합니다."},
		LastLessonRule:          "마지막 lesson은 실기 시험 직전까지 작업 순서와 위생 기준을 점검하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 시험 응시와 자격 취득은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"도구 소개만 보기", "위생 규정만 읽기"},
	},
	"craft_making:artifact_creation:local_hobby_workshop_series": {
		Name:                    "지역 생활취미 워크숍형",
		StepRoles:               []string{"setup_intro", "first_output", "core_pattern", "integration_practice", "artifact_finish"},
		StageRules:              []string{"리슨은 지역센터 강좌의 접수나 출석보다 도구와 수업 방식 입문, 첫 결과물, 핵심 기법 반복, 피드백 반영, 작은 작품 완성으로 이어져야 합니다.", "오프라인 수업 피드백은 독립 리슨이 아니라 결과물을 개선하는 단계 안에 둡니다."},
		LastLessonRule:          "마지막 lesson은 수업 피드백을 반영해 작은 결과물 한 점을 완성하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"접수 성공, 출석, 수강료 납부는 completion_criteria 또는 참여 조건으로 분리합니다."},
		AtomicDisallowExamples:  []string{"수강 신청", "출석하기", "준비물 목록만 보기"},
	},
}
