package curriculum

var goalSubpatternSpecsInstrumentLanguageBody = map[string]goalSubpatternSpec{
	"instrument_performance:participation_service:worship_team_support": {
		Name:                    "찬양단/워십팀 참여형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "performance_prep"},
		StageRules:              []string{"리슨은 솔로 연주보다 반주 연결과 시작/진행/마침 타이밍 적응에 초점을 둡니다.", "과하게 튀는 표현보다 합주 흐름을 지탱하는 반주 연결 능력을 우선합니다."},
		LastLessonRule:          "마지막 lesson은 찬양단 합주 흐름에 맞춰 반주를 준비하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 찬양단 봉사, 공식 워십팀 참여는 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"튜닝", "기본 자세", "오픈 코드 하나"},
	},
	"instrument_performance:performance_execution:song_completion": {
		Name:                    "한 곡 완주형",
		StepRoles:               []string{"setup_intro", "first_output", "integration_practice", "performance_prep"},
		StageRules:              []string{"리슨은 기술 소개보다 목표 곡의 구간 연결과 완주 흐름에 초점을 둡니다.", "중간 리슨은 곡 일부 연습이 아니라 처음부터 끝까지 이어가는 관문이 드러나야 합니다."},
		LastLessonRule:          "마지막 lesson은 목표 곡을 끝까지 이어갈 직전 준비 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 공연이나 무대 발표는 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"기본 자세", "스케일 소개", "양손 모양"},
	},
	"body_movement:performance_execution:dance_cover_song_routine": {
		Name:                    "댄스 커버 한 곡 루틴형",
		StepRoles:               []string{"setup_intro", "first_output", "core_pattern", "integration_practice", "performance_prep"},
		StageRules:              []string{"리슨은 스트레칭이나 리듬 설명만으로 분리하지 말고 목표 안무의 구간 학습, 동작 연결, 음악 박자 맞춤, 전체 루틴 통합으로 이어져야 합니다.", "케이팝 댄스 커버 목표에서는 후렴이나 포인트 안무만 떼어내지 말고 한 곡 흐름 안에서 구간별 연결을 점검해야 합니다."},
		LastLessonRule:          "마지막 lesson은 좋아하는 곡의 안무를 처음부터 끝까지 이어갈 직전 리허설 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 영상 촬영, SNS 업로드, 공연 참여는 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"기본 리듬 설명만 보기", "포인트 안무 하나만 따라 하기", "스트레칭만 하기"},
	},
	"body_movement:habit_lifestyle:running_5k_beginner_routine": {
		Name:                    "초보 5km 러닝 루틴형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "routine_plan"},
		StageRules:              []string{"리슨은 러닝화나 기록 앱 소개만으로 분리하지 말고 걷기·조깅 시작, 자세와 호흡, 인터벌 반복, 5km 완주 루틴 계획으로 이어져야 합니다.", "초보 러닝 목표에서는 속도보다 부상 예방, 페이스 조절, 회복일 배치, 꾸준한 거리 증가를 우선합니다."},
		LastLessonRule:          "마지막 lesson은 5km 완주를 향한 주간 러닝 루틴과 회복 계획을 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 대회 참가, 체중 감량, 기록 단축, 장기 운동 습관은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"러닝화 비교만 보기", "앱 설치만 하기", "무리한 전력질주만 하기"},
	},
	"body_movement:habit_lifestyle:yoga_daily_routine": {
		Name:                    "요가 데일리 루틴형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "routine_plan"},
		StageRules:              []string{"리슨은 요가 자세 이름을 나열하지 말고 호흡, 기본 자세, 안전한 전환, 짧은 루틴 구성, 반복 가능한 실천 흐름으로 이어져야 합니다.", "초보 루틴 목표에서는 무리한 고난도 자세보다 매일 반복 가능한 시간과 강도 조절이 드러나야 합니다."},
		LastLessonRule:          "마지막 lesson은 스스로 이어갈 수 있는 10~20분 요가 루틴을 구성하고 실천 준비를 마치는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"주간 루틴 정착, 체중 감량, 통증 개선 같은 장기 결과는 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"자세 이름만 외우기", "호흡 설명만 보기", "고난도 자세 하나만 따라 하기"},
	},
	"body_movement:habit_lifestyle:home_strength_routine": {
		Name:                    "홈 근력 루틴형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "routine_plan"},
		StageRules:              []string{"리슨은 운동 이름을 나열하지 말고 안전한 자세, 대표 동작 패턴, 세트 구성, 주간 반복 루틴으로 이어져야 합니다.", "초보 홈트 목표에서는 고강도 챌린지보다 맨몸·덤벨 기반의 반복 가능한 강도 조절과 부상 예방을 우선합니다."},
		LastLessonRule:          "마지막 lesson은 스스로 이어갈 수 있는 20~30분 홈 근력 루틴을 구성하고 다음 주 실천 준비를 마치는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"체중 감량, 근육량 증가, 장기 운동 습관 정착은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"운동 이름만 외우기", "스트레칭만 하기", "고강도 챌린지 하나만 따라 하기"},
	},
	"language_communication:performance_execution:daily_english_conversation_routine": {
		Name:                    "일상 영어회화 루틴형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "performance_prep"},
		StageRules:              []string{"리슨은 문법 항목 암기보다 매일 쓰는 상황 표현, 짧은 문장 말하기, 쉐도잉, 역할극, 자기 일상 설명 흐름으로 이어져야 합니다.", "일상 회화 목표에서는 시험 점수보다 반복 가능한 말하기 루틴과 상황별 응답 능력을 우선합니다."},
		LastLessonRule:          "마지막 lesson은 하루 일상과 자주 겪는 상황을 영어로 말하기 직전까지 표현 흐름을 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 해외여행, 시험 응시, 장기 회화 유창성은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"문법 정의만 보기", "단어장만 외우기", "표현 목록만 저장하기"},
	},
	"language_communication:performance_execution:travel_conversation": {
		Name:                    "여행 회화형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "performance_prep"},
		StageRules:              []string{"리슨은 문법 설명보다 여행 상황에서 바로 쓰는 질문과 응답 흐름에 초점을 둡니다.", "공항, 식당, 길 묻기처럼 짧은 상황 대화를 자연스럽게 잇는 단계가 포함되어야 합니다."},
		LastLessonRule:          "마지막 lesson은 여행 상황에서 실제 대화를 시작하기 직전 표현 흐름을 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 해외 여행에서 자연스럽게 말하기는 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"문법 설명", "표현 목록만 외우기", "발음 설명만 보기"},
	},
	"language_communication:certification_assessment:exam_targeted_language": {
		Name:                    "언어 시험 준비형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "performance_prep"},
		StageRules:              []string{"리슨은 회화형 상황 연습보다 시험 범위와 유형별 풀이 흐름에 초점을 둡니다.", "JLPT처럼 영역이 분명한 시험은 어휘·문법·독해와 청해 흐름이 자연스럽게 이어져야 합니다."},
		LastLessonRule:          "마지막 lesson은 시험 직전까지 영역별 문제 흐름을 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 시험 응시와 합격은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"문자표만 보기", "문법 정의만 외우기"},
	},
	"language_communication:certification_assessment:english_score_exam_certification": {
		Name:                    "영어 점수형 시험 준비형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "performance_prep"},
		StageRules:              []string{"리슨은 회화형 상황 대화보다 파트 구조와 점수형 문제풀이 흐름에 초점을 둡니다.", "TOEIC·TEPS처럼 어휘·문법·독해·청해가 나뉜 시험은 파트별 시간 대응과 오답 패턴 정리가 포함되어야 합니다."},
		LastLessonRule:          "마지막 lesson은 시험 직전까지 파트별 문제풀이와 시간 운영 흐름을 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 시험 응시와 목표 점수 달성은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"표현 목록만 외우기", "문법 정의만 보기"},
	},
	"language_communication:certification_assessment:english_speaking_interview_certification": {
		Name:                    "영어 말하기 인터뷰 시험형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "performance_prep"},
		StageRules:              []string{"리슨은 객관식 문제풀이보다 인터뷰 답변 흐름과 즉흥 응답에 초점을 둡니다.", "자기소개, 주제 확장, 경험 말하기, 돌발 질문 대응이 자연스럽게 이어져야 합니다."},
		LastLessonRule:          "마지막 lesson은 시험 직전까지 인터뷰 흐름과 답변 길이 조절을 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 시험 응시와 목표 등급 획득은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"표현 목록만 암기하기", "질문 유형만 나열하기"},
	},
	"language_communication:certification_assessment:english_integrated_four_skills_certification": {
		Name:                    "영어 4영역 통합 시험형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "performance_prep"},
		StageRules:              []string{"리슨은 회화형이나 점수형 단일 파트보다 Reading, Listening, Writing, Speaking의 통합 운영에 초점을 둡니다.", "IELTS·TOEFL처럼 task 전환과 integrated response가 중요한 시험은 영역 간 연결이 드러나야 합니다."},
		LastLessonRule:          "마지막 lesson은 시험 직전까지 4영역 task 전환과 시간 배분 흐름을 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 시험 응시와 목표 점수 달성은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"단어장만 보기", "문법 정의만 외우기"},
	},
	"instrument_performance:performance_execution:vocal_song_practice": {
		Name:                    "보컬 한 곡 연습형",
		StepRoles:               []string{"setup_intro", "first_output", "core_pattern", "integration_practice", "performance_prep"},
		StageRules:              []string{"리슨은 발성 이론만 나누지 말고 호흡·음정·리듬을 목표 곡의 구간 연습과 연결해야 합니다.", "초보 보컬 목표에서는 고음 과시보다 안정적인 호흡, 정확한 음정, 가사 전달, 한 곡 리허설 흐름을 우선합니다."},
		LastLessonRule:          "마지막 lesson은 목표 곡을 처음부터 끝까지 부르기 직전까지 호흡, 음정, 표현을 점검하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 녹음 공개, 무대 공연, 보컬 오디션 응시는 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"호흡 설명만 보기", "발성 용어만 외우기", "고음 클립만 따라 하기"},
	},
	"instrument_performance:performance_execution:song_driven_instrument_path": {
		Name:                    "영어 song-driven instrument path형",
		StepRoles:               []string{"setup_intro", "first_output", "core_pattern", "integration_practice", "performance_prep"},
		StageRules:              []string{"리슨은 짧은 skill video를 그대로 나열하지 말고 악기·스타일 path 설정, 첫 riff/skill, chord와 technique 반복, song 적용, 연주 직전 준비로 묶습니다.", "튜닝과 chord 이름은 독립 리슨이 아니라 첫 소리와 곡 적용 흐름 안에 흡수합니다."},
		LastLessonRule:          "마지막 lesson은 목표 곡이나 대표 song section을 연주 직전까지 연결하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 공연, 녹음 공개, 유료 구독, 공식 feedback 제출은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"2~8분 skill video 하나", "튜닝만 하기", "chord 이름만 보기"},
	},
}
