package curriculum

var goalSubpatternSpecsKnowledge = map[string]goalSubpatternSpec{
	"knowledge_hobby:foundation_build:mooc_humanities_survey": {
		Name:                    "영어 MOOC 인문 survey형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "publish_prep"},
		StageRules:              []string{"리슨은 강의 주차를 그대로 복제하지 말고 시대·주제 맥락, 핵심 작품·텍스트·사례군, 비평·토론 적용, 글쓰기·발표 직전 정리의 큰 관문으로 압축합니다.", "작품명, 연도, 용어 암기는 독립 리슨이 아니라 비교·해석 단계 안의 학습 활동으로 흡수합니다."},
		LastLessonRule:          "마지막 lesson은 토론, 글쓰기, 발표 직전까지 핵심 사례를 자기 관점으로 종합 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 paper 제출, 공식 발표, MOOC 수료, 학점 취득은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"작품명만 보기", "작곡가 이름만 외우기", "연도만 암기하기", "reading 하나만 읽기"},
	},
	"knowledge_hobby:habit_lifestyle:digital_literacy_badged_course": {
		Name:                    "영어 디지털 리터러시 badged course형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice"},
		StageRules:              []string{"리슨은 온라인 계정 만들기나 보안 용어 암기보다 현재 디지털 생활 진단, 안전·정체성·도구 선택 패턴, 실제 상황 적용, 개인 실천 계획으로 이어져야 합니다.", "badge, quiz, certificate는 독립 리슨이 아니라 각 단계의 확인 활동이나 completion 기준으로 둡니다."},
		LastLessonRule:          "마지막 lesson은 학습자 상황에 맞는 디지털 스킬 실천 계획을 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 badge 획득, course 수료, 장기 실천 유지 자체는 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"계정 만들기만 하기", "보안 용어만 읽기", "badge 이름만 확인하기"},
	},
	"knowledge_hobby:foundation_build:open_textbook_chapter_practice": {
		Name:                    "영어 open textbook chapter practice형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "performance_prep"},
		StageRules:              []string{"리슨은 textbook chapter를 그대로 복제하지 말고 과목 범위, 핵심 chapter 묶음, 연습문제 적용, 시험·토론 직전 정리의 큰 관문으로 압축합니다.", "chapter 제목이나 용어 정의 하나는 독립 리슨이 아니라 개념 묶음 안의 활동입니다."},
		LastLessonRule:          "마지막 lesson은 핵심 개념을 연습문제나 토론 준비 수준으로 통합 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"교재 완독, 공식 시험, 학점 취득은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"chapter 제목 하나", "용어 정의 하나", "연습문제 하나"},
	},
	"knowledge_hobby:foundation_build:oer_learning_object_cluster": {
		Name:                    "영어 OER learning object cluster형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice"},
		StageRules:              []string{"리슨은 learning object 하나를 그대로 옮기지 말고 textbook, worksheet, simulation, visualization을 개념 이해와 적용 활동으로 묶습니다.", "object의 형식보다 학습자가 무엇을 이해하고 적용하는지가 lesson 경계가 되어야 합니다."},
		LastLessonRule:          "마지막 lesson은 여러 OER object를 활용해 핵심 개념을 적용하거나 설명할 수 있게 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"worksheet 제출, 공식 course 수료, 시험 응시는 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"object 하나만 보기", "worksheet 하나만 풀기", "simulation만 켜보기"},
	},
	"knowledge_hobby:foundation_build:interactive_tutor_concept_practice": {
		Name:                    "영어 interactive tutor concept practice형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "performance_prep"},
		StageRules:              []string{"리슨은 objective, tutor 문제, quiz를 따로 쪼개지 말고 학습목표 확인, 핵심 개념 설명, interactive tutor practice, 이해 점검으로 묶습니다.", "피드백 기반 반복이 핵심이므로 개념 설명과 guided practice가 같은 관문 안에서 연결되어야 합니다."},
		LastLessonRule:          "마지막 lesson은 tutor feedback을 바탕으로 약점을 정리하고 다음 단원 또는 평가 직전 준비를 마치는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"quiz 통과, 공식 course 완료, 시험 응시는 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"tutor 문제 하나", "quiz 하나", "objective 하나"},
	},
	"knowledge_hobby:concept_mastery:science_simulation_inquiry_path": {
		Name:                    "영어 science simulation inquiry형",
		StepRoles:               []string{"setup_intro", "prediction_prompt", "interactive_exploration", "variable_experiment", "explanation_finish"},
		StageRules:              []string{"리슨은 simulation을 단순 클릭하는 순서가 아니라 현상 질문, 예측, 조작, 변수 비교, 원리 설명으로 이어져야 합니다.", "slider나 measurement tool 같은 조작은 독립 리슨이 아니라 예측을 검증하는 탐구 활동으로 흡수합니다."},
		LastLessonRule:          "마지막 lesson은 관찰과 변수 비교를 바탕으로 원리를 자기 말로 설명하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"simulation 완료 표시나 worksheet 제출은 completion_criteria로 분리할 수 있습니다."},
		AtomicDisallowExamples:  []string{"simulation 켜보기", "slider 하나 움직이기", "정의 하나 읽기"},
	},
	"knowledge_hobby:concept_mastery:guided_simulation_activity_sheet": {
		Name:                    "영어 guided simulation activity sheet형",
		StepRoles:               []string{"setup_intro", "structure_plan", "interactive_exploration", "peer_discussion", "reflection_finish"},
		StageRules:              []string{"리슨은 worksheet 빈칸 채우기보다 탐구 질문과 simulation exploration, 관찰 공유, reflection으로 이어져야 합니다.", "activity sheet prompt는 독립 리슨이 아니라 탐구 흐름을 안내하는 구조로 사용합니다."},
		LastLessonRule:          "마지막 lesson은 관찰 결과와 discussion을 바탕으로 reflection을 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"worksheet 제출이나 group discussion 참여 자체는 completion_criteria로 분리할 수 있습니다."},
		AtomicDisallowExamples:  []string{"worksheet 하나 채우기", "정답 확인만 하기", "discussion 없이 조작만 하기"},
	},
	"knowledge_hobby:concept_mastery:horticulture_diagnostic_foundation": {
		Name:                    "영어 horticulture diagnostic foundation형",
		StepRoles:               []string{"setup_intro", "core_pattern", "structure_plan", "diagnostic_practice", "integration_practice", "artifact_finish"},
		StageRules:              []string{"리슨은 botany, soil, IPM, pathology, plant group 지식을 식물 관리 진단과 care plan으로 연결해야 합니다.", "certificate나 volunteering은 lesson 경계가 아니라 후속 목표 또는 completion 기준으로 분리합니다."},
		LastLessonRule:          "마지막 lesson은 학습자 식물 또는 정원 상황에 맞는 진단 plan과 care routine을 완성하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"Master Gardener volunteering, certificate, 장기 재배 성공은 completion_criteria 또는 후속 목표로 분리합니다."},
		AtomicDisallowExamples:  []string{"식물 이름만 외우기", "pest 이름만 보기", "certificate 등록"},
	},
	"knowledge_hobby:concept_mastery:climate_data_graphing_explanation": {
		Name:                    "영어 climate data graphing explanation형",
		StepRoles:               []string{"context_intro", "data_reading", "model_build", "trend_compare", "explanation_finish"},
		StageRules:              []string{"리슨은 climate claim을 읽는 데서 끝나지 않고 temperature anomaly data, axis, graph model, short/long trend 비교, evidence-based explanation으로 이어져야 합니다.", "그래프 이미지만 보는 활동은 독립 리슨이 아니라 데이터 해석과 설명 단계 안에 둡니다."},
		LastLessonRule:          "마지막 lesson은 데이터와 그래프를 근거로 trend 설명을 완성하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"공식 과제 제출, 장기 데이터 분석 프로젝트 완성은 completion_criteria 또는 후속 목표로 분리합니다."},
		AtomicDisallowExamples:  []string{"그래프 보기만 하기", "결론 암기하기", "데이터 없이 주장 쓰기"},
	},
	"knowledge_hobby:habit_lifestyle:citizen_science_observation_record": {
		Name:                    "영어 citizen science observation record형",
		StepRoles:               []string{"safety_intro", "field_setup", "observation_capture", "identification_practice", "community_record_finish"},
		StageRules:              []string{"리슨은 관찰 수 경쟁보다 안전한 field setup, 사진과 메모 수집, field guide/iNaturalist 식별, biodiversity record 정리로 이어져야 합니다.", "public upload는 정확한 관찰 기록을 확인하는 completion 기준으로 두고 lesson 자체로 만들지 않습니다."},
		LastLessonRule:          "마지막 lesson은 관찰 근거와 식별 과정을 정리한 biodiversity record를 마무리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 공개 업로드 수, BioBlitz 참여, volunteer requirement는 completion_criteria 또는 후속 목표로 분리합니다."},
		AtomicDisallowExamples:  []string{"species 이름만 외우기", "사진만 업로드하기", "관찰 수 경쟁"},
	},
	"knowledge_hobby:concept_mastery:primary_source_inquiry_note": {
		Name:                    "영어 primary source inquiry note형",
		StepRoles:               []string{"source_setup", "observation_practice", "reflection_practice", "question_generation", "investigation_finish"},
		StageRules:              []string{"리슨은 자료 읽기나 역사 배경 암기에서 끝나지 않고 observe, reflect, question, investigate further의 inquiry loop로 구성합니다.", "source type별 prompt는 독립 리슨이 아니라 관찰 근거와 질문을 만드는 활동으로 둡니다."},
		LastLessonRule:          "마지막 lesson은 추가 조사 방향과 짧은 해석 note를 완성하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"공식 essay 제출, 전시 제작, 장기 research project는 completion_criteria 또는 후속 목표로 분리합니다."},
		AtomicDisallowExamples:  []string{"자료 하나 읽기", "역사 배경 암기", "질문 없이 요약만 하기"},
	},
	"knowledge_hobby:professional_transition:short_diploma_assessment_path": {
		Name:                    "영어 short diploma assessment path형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "performance_prep"},
		StageRules:              []string{"리슨은 module 제목을 복제하지 말고 직무·생활 목표 선택, 핵심 module 묶음, 실무 적용 관점 정리, assessment/diploma 직전 준비로 압축합니다.", "certificate 구매나 learner record 다운로드는 lesson이 아니라 completion 기준 또는 후속 행동으로 둡니다."},
		LastLessonRule:          "마지막 lesson은 assessment 또는 diploma 직전까지 핵심 내용을 적용 관점으로 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 diploma 발급, certificate 구매, 취업 지원은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"certificate 구매", "learner record 다운로드", "모듈 제목 하나"},
	},
	"knowledge_hobby:foundation_build:short_course_weekly_discussion": {
		Name:                    "영어 short course weekly discussion형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "performance_prep"},
		StageRules:              []string{"리슨은 week 하나를 그대로 복제하지 말고 주제와 수준 선택, 핵심 week 묶음, discussion/case 적용, short course completion 직전 정리로 구성합니다.", "discussion 하나는 독립 리슨보다 개념을 자기 관점으로 적용하는 활동으로 둡니다."},
		LastLessonRule:          "마지막 lesson은 short course completion 직전까지 핵심 사례와 토론 관점을 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 course 수료, upgrade, certificate 발급은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"week 하나 복제", "discussion 하나만 쓰기", "upgrade 버튼 누르기"},
	},
	"knowledge_hobby:foundation_build:audit_course_practice_path": {
		Name:                    "영어 audit course practice path형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "performance_prep"},
		StageRules:              []string{"리슨은 lecture 하나를 옮기지 말고 audit course 선택, lecture/readings 핵심 묶음, ungraded practice와 discussion 적용, 다음 학습 직전 정리로 구성합니다.", "audit 등록이나 verified upgrade는 lesson이 아니라 completion 기준 또는 별도 후속 행동입니다."},
		LastLessonRule:          "마지막 lesson은 audit 학습 내용을 다음 학습이나 verified track 전환 직전까지 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 verified upgrade, certificate 발급, 공식 과제 제출은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"lecture 하나 보기", "audit 등록", "certificate upgrade 자체"},
	},
	"knowledge_hobby:habit_lifestyle:garden_design_maintenance_path": {
		Name:                    "영어 garden design maintenance path형",
		StepRoles:               []string{"setup_intro", "structure_plan", "core_pattern", "integration_practice", "artifact_finish"},
		StageRules:              []string{"리슨은 식물 이름이나 tool 하나를 고르는 단계가 아니라 정원 목표와 공간 파악, garden design plan, planting/installation 핵심 패턴, maintenance routine 적용, 작은 garden plan 완성으로 이어져야 합니다.", "생활형 garden 목표는 설치보다 유지관리 루틴이 함께 보여야 합니다."},
		LastLessonRule:          "마지막 lesson은 자기 공간에 맞는 작은 garden plan과 유지관리 루틴을 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"certificate, 유료 design tool 사용, 실제 정원 완성은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"tool 하나 보기", "certificate만 받기", "식물 이름만 고르기"},
	},
	"knowledge_hobby:habit_lifestyle:houseplant_repotting_care": {
		Name:                    "반려식물 분갈이 관리형",
		StepRoles:               []string{"setup_intro", "structure_plan", "core_pattern", "integration_practice", "routine_plan"},
		StageRules:              []string{"리슨은 식물 이름 고르기나 일반 원예 이론보다 현재 화분 상태 확인, 흙/화분 선택, 안전한 분갈이, 회복 관찰, 이후 관리 루틴으로 이어져야 합니다.", "houseplant 목표에서는 분갈이 직후 물주기, 빛, 스트레스 징후 관찰이 마지막 관리 루틴에 포함되어야 합니다."},
		LastLessonRule:          "마지막 lesson은 분갈이한 식물의 회복 상태를 점검하고 다음 물주기와 빛 관리 루틴을 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"장기 생장 성공, 희귀 식물 수집, 전문 원예 자격은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"식물 이름만 외우기", "흙 종류만 비교하기", "화분 쇼핑만 하기"},
	},
	"knowledge_hobby:habit_lifestyle:personal_finance_budget_routine": {
		Name:                    "개인 예산 관리 루틴형",
		StepRoles:               []string{"setup_intro", "structure_plan", "core_pattern", "integration_practice", "routine_plan"},
		StageRules:              []string{"리슨은 투자나 수익률보다 수입/고정비 파악, 지출 카테고리 설계, 예산표 작성, 1주 지출 기록, 주간 리뷰 루틴으로 이어져야 합니다.", "초보 재정 목표에서는 실제 금액을 입력하고 다음 주 조정 기준을 만드는 행동이 포함되어야 합니다."},
		LastLessonRule:          "마지막 lesson은 첫 주 지출 기록을 검토하고 다음 주 예산 조정 루틴을 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"투자 수익, 대출 상담, 세무 자문, 장기 자산 목표 달성은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"투자상품만 비교하기", "예산 이론만 읽기", "앱 설치만 하기"},
	},
	"knowledge_hobby:habit_lifestyle:dog_basic_training_routine": {
		Name:                    "반려견 기본 훈련 루틴형",
		StepRoles:               []string{"setup_intro", "core_pattern", "first_output", "integration_practice", "routine_plan"},
		StageRules:              []string{"리슨은 훈련 이론만 설명하지 말고 보상 준비, 짧은 세션 구조, sit/stay/come 명령, 산만한 환경에서의 반복, 안전한 일상 루틴 적용으로 이어져야 합니다.", "반려견 훈련 목표에서는 강압적 방법이 아니라 positive reinforcement와 짧은 반복을 기준으로 구성합니다."},
		LastLessonRule:          "마지막 lesson은 세 가지 기본 명령을 짧은 실제 세션에서 연결하고 다음 반복 루틴을 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"전문 행동교정, 공격성 문제 해결, 자격증 취득은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"명령어 이름만 보기", "간식 쇼핑만 하기", "문제행동 진단만 하기"},
	},
	"knowledge_hobby:habit_lifestyle:organic_growing_cycle_plan": {
		Name:                    "영어 organic growing cycle plan형",
		StepRoles:               []string{"setup_intro", "core_pattern", "structure_plan", "integration_practice", "artifact_finish"},
		StageRules:              []string{"리슨은 crop 이름이나 season 표 암기에 머물지 말고 organic growing 입문, crop/season 핵심 패턴, sowing plan, care routine 통합, 첫 growing cycle 준비로 이어져야 합니다.", "생활형 organic growing은 수확 성공보다 반복 가능한 재배 계획과 관리 루틴을 우선합니다."},
		LastLessonRule:          "마지막 lesson은 첫 growing cycle을 시작할 수 있게 crop, season, sowing, care routine을 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 수확 성공, certificate, 농업 창업은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"crop 이름만 보기", "season 표만 외우기", "certificate만 받기"},
	},
	"knowledge_hobby:certification_assessment:counseling_certification": {
		Name:                    "상담 이론 자격형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "performance_prep"},
		StageRules:              []string{"리슨은 개념 암기보다 상담 이론, 직업 정보, 노동시장 이해를 문제풀이 흐름으로 연결하는 데 초점을 둡니다.", "암기 범위가 넓은 시험이므로 영역별 정리와 기출형 적용이 포함되어야 합니다."},
		LastLessonRule:          "마지막 lesson은 시험 직전까지 주요 이론과 문제풀이 흐름을 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 시험 응시와 자격 취득은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"이론 이름만 나열하기", "정의만 외우기"},
	},
	"knowledge_hobby:certification_assessment:environmental_engineering_certification": {
		Name:                    "환경 기사형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "performance_prep"},
		StageRules:              []string{"리슨은 대기 오염 기초, 방지 기술, 법규를 실제 문제풀이 흐름으로 연결하는 데 초점을 둡니다.", "공정·기술·법규가 따로 놀지 않게 시험형 통합 단계가 포함되어야 합니다."},
		LastLessonRule:          "마지막 lesson은 시험 직전까지 핵심 기술과 문제풀이 흐름을 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 시험 응시와 자격 취득은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"법규 목록만 보기", "용어 정의만 외우기"},
	},
	"knowledge_hobby:habit_lifestyle:public_lifelong_online_course": {
		Name:                    "공공 평생학습 온라인 강좌형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "performance_prep"},
		StageRules:              []string{"리슨은 플랫폼 강좌 목록을 그대로 복제하지 말고 학습자의 생활 목표에 맞춘 강좌 묶음, 핵심 개념, 생활 적용, 수료 직전 정리로 압축합니다.", "회원가입, 쿠폰, 수료증 출력 같은 운영 요소는 독립 리슨이 아니라 준비 또는 완료 기준으로 둡니다."},
		LastLessonRule:          "마지막 lesson은 온라인 강좌에서 배운 내용을 실제 생활 실천 계획으로 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 수료증 발급, 할인쿠폰 사용, 플랫폼 혜택 수령은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"회원가입만 하기", "강좌 목록 둘러보기", "수료증 출력"},
	},
	"knowledge_hobby:participation_service:blended_lifelong_participation": {
		Name:                    "온·오프라인 평생학습 참여형",
		StepRoles:               []string{"setup_intro", "structure_plan", "core_pattern", "participation_prep", "integration_practice"},
		StageRules:              []string{"리슨은 온라인 선행학습, 오프라인/화상 강좌 선택, 참여 준비, 학습이력 정리를 하나의 blended learning 흐름으로 묶습니다.", "강좌 접수와 출석 자체보다 참여 전 준비와 이후 학습 연결 역량을 우선합니다."},
		LastLessonRule:          "마지막 lesson은 참여한 학습 내용을 이력과 다음 강좌 계획으로 연결하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 오프라인 강좌 등록, 출석, 수강료 납부는 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"접수하기", "강좌 장소 확인", "출석만 하기"},
	},
	"knowledge_hobby:professional_transition:midlife_transition_learning_support": {
		Name:                    "중장년 전환 학습지원형",
		StepRoles:               []string{"setup_intro", "structure_plan", "core_pattern", "integration_practice", "performance_prep"},
		StageRules:              []string{"리슨은 지원사업 신청 절차보다 전환 목표 진단, 학습경로 선택, 핵심 직무역량 학습, 적용 과제, 취·창업 직전 계획으로 구성합니다.", "중장년 학습자는 기존 경험과 새 역량을 연결하는 단계가 반드시 보여야 합니다."},
		LastLessonRule:          "마지막 lesson은 취·창업 또는 직무 전환 직전의 학습 포트폴리오와 다음 행동 계획을 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"학습경비 신청, 포인트 수령, 실제 취업·창업 성공은 completion_criteria 또는 후속 목표로 분리합니다."},
		AtomicDisallowExamples:  []string{"지원금 신청만 하기", "교육기관 목록 보기", "취업 성공 자체"},
	},
	"knowledge_hobby:professional_transition:completion_refund_online_course": {
		Name:                    "수료·환급형 온라인 과정",
		StepRoles:               []string{"setup_intro", "structure_plan", "core_pattern", "performance_prep"},
		StageRules:              []string{"리슨은 할인이나 환급 조건보다 강좌 선택 기준, 진도 관리 계획, 핵심 내용 학습, 수료 직전 적용 정리로 잡습니다.", "진도율과 환급은 학습 진행을 관리하는 기준으로 두고 lesson 경계로 만들지 않습니다."},
		LastLessonRule:          "마지막 lesson은 수료 기준을 충족하기 직전까지 핵심 내용을 실제 적용 계획으로 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"결제, 환급, 수료증 발급은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"결제하기", "진도율 숫자 맞추기", "환급 신청"},
	},
	"knowledge_hobby:foundation_build:federated_lifelong_open_resource": {
		Name:                    "평생학습 공개자료 묶음 설계형",
		StepRoles:               []string{"setup_intro", "structure_plan", "core_pattern", "integration_practice"},
		StageRules:              []string{"리슨은 흩어진 공개강좌 링크 수집에서 끝나지 않고 학습 주제 정의, 강좌 묶음 설계, 핵심 콘텐츠 학습, 자기주도 학습계획 정리로 이어져야 합니다.", "플랫폼 탐색은 독립 리슨이 아니라 목표별 학습경로 설계 안에 흡수합니다."},
		LastLessonRule:          "마지막 lesson은 공개 평생학습 자료를 자기 상황에 맞는 학습계획으로 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"플랫폼 가입, 링크 북마크, 외부 강좌 공식 수료는 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"링크 모으기", "포털 둘러보기", "강좌명만 비교하기"},
	},
	"knowledge_hobby:professional_transition:rural_return_agriculture_foundation": {
		Name:                    "귀농귀촌 농업 기초형",
		StepRoles:               []string{"setup_intro", "structure_plan", "core_pattern", "integration_practice", "performance_prep"},
		StageRules:              []string{"리슨은 귀농귀촌 정보 수집, 정착 목표와 품목 후보 정리, 기초 품목기술, 교육시간/수료 관리, 정착 준비 계획으로 이어져야 합니다.", "정책지원 신청이나 실제 이주는 lesson이 아니라 완료 기준 또는 후속 목표로 둡니다."},
		LastLessonRule:          "마지막 lesson은 정착 후보와 품목 학습 내용을 바탕으로 귀농귀촌 준비 계획을 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"정책지원 신청, 실제 이주, 농지 확보, 장기 수익화는 completion_criteria 또는 후속 목표로 분리합니다."},
		AtomicDisallowExamples:  []string{"지원사업 신청", "지역 목록만 보기", "농지 계약"},
	},
	"knowledge_hobby:habit_lifestyle:urban_agriculture_practice_series": {
		Name:                    "도시농업 실습 시리즈형",
		StepRoles:               []string{"setup_intro", "structure_plan", "core_pattern", "integration_practice", "artifact_finish"},
		StageRules:              []string{"리슨은 도시농업 입문, 텃밭/화분 구조 계획, 작물 재배 핵심, 원예 실습 적용, 생활 관리 루틴으로 이어져야 합니다.", "재배 도구나 작물명 소개만 분리하지 말고 실제 돌봄과 관찰 루틴 안에 흡수합니다."},
		LastLessonRule:          "마지막 lesson은 작은 텃밭이나 화분 관리 루틴을 완성하고 다음 재배 주기를 계획하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"도시농업전문가 활동, 실제 텃밭 분양, 장기 수확 성공은 completion_criteria 또는 후속 목표로 분리합니다."},
		AtomicDisallowExamples:  []string{"작물 이름만 외우기", "도구 목록만 보기", "텃밭 신청"},
	},
	"knowledge_hobby:habit_lifestyle:ai_digital_literacy_life_practice": {
		Name:                    "AI·디지털 생활문해 실천형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "safety_check", "performance_prep"},
		StageRules:              []string{"리슨은 스마트폰 기초, 생활앱 사용, 키오스크/예약 실습, AI 이해와 활용, 보안·보이스피싱 점검을 실제 생활 행동으로 묶습니다.", "특정 앱 설치나 교육 신청보다 안전하게 반복 가능한 생활 과제 수행을 우선합니다."},
		LastLessonRule:          "마지막 lesson은 디지털 생활 과제를 안전하게 반복할 수 있는 개인 루틴을 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"배움터 방문, 교육 신청, 특정 앱 설치는 completion_criteria 또는 준비 조건으로 분리합니다."},
		AtomicDisallowExamples:  []string{"앱 설치만 하기", "버튼 이름만 외우기", "키오스크 화면 보기만 하기"},
	},
	"knowledge_hobby:habit_lifestyle:university_survey": {
		Name:                    "대학 survey형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice"},
		StageRules:              []string{"리슨은 주차별 세부 주제를 잘게 쪼개지 말고 시대 흐름, 핵심 텍스트나 사례군, 비교·비평 관점의 큰 묶음으로 구성합니다.", "후반에는 단일 사실 암기보다 여러 사례를 비교하고 해석해 종합하는 단계가 반드시 포함되어야 합니다."},
		LastLessonRule:          "마지막 lesson은 여러 사례를 비교·비평·종합 관점으로 연결해 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 paper 제출, 공식 수강 완료, 학점 취득은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"작가 이름만 외우기", "연도만 암기하기", "용어 정의만 읽기"},
	},
	"knowledge_hobby:habit_lifestyle:kmooc_online_course_survey": {
		Name:                    "K-MOOC 온라인 공개강좌형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "performance_prep"},
		StageRules:              []string{"리슨은 K-MOOC 주차를 그대로 복제하지 말고 강좌 범위, 핵심 주제 묶음, 퀴즈·사례 적용, 평가 직전 통합 정리의 큰 관문으로 압축합니다.", "동영상·PDF·퀴즈 같은 운영 요소는 독립 리슨이 아니라 각 관문 안의 학습 활동으로 흡수합니다."},
		LastLessonRule:          "마지막 lesson은 공개강좌 평가 직전까지 핵심 주제와 사례 적용 흐름을 통합 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 K-MOOC 수강 완료, 시험 제출, 이수증 발급은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"오리엔테이션만 보기", "PDF 다운로드", "퀴즈 제출", "주차명 하나만 학습"},
	},
	"knowledge_hobby:foundation_build:korean_open_lecture_weekly_survey": {
		Name:                    "한국 공개강의 주차형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice", "core_pattern", "performance_prep"},
		StageRules:              []string{"리슨은 K-MOOC/KOCW의 15주·16주 주차표를 그대로 복제하지 말고 강좌 범위, 개념 묶음, 사례나 문제 적용, 후반 통합, 평가 직전 정리의 큰 관문으로 압축합니다.", "주차명, 차시명, 교재 범위는 독립 lesson이 아니라 관문 안의 학습 활동이나 참고 자료로 흡수합니다."},
		LastLessonRule:          "마지막 lesson은 공개강의 평가나 자기점검 직전까지 핵심 주제와 적용 흐름을 통합 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"영상 시청률, PDF 다운로드, 퀴즈 제출, 공식 시험 응시, 학점·이수증 취득은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"주차명 하나만 학습", "PDF 다운로드", "퀴즈 제출", "시험 보기"},
	},
	"knowledge_hobby:professional_transition:credit_bank_practicum": {
		Name:                    "학점은행제 실습형",
		StepRoles:               []string{"setup_intro", "structure_plan", "integration_practice", "performance_prep"},
		StageRules:              []string{"리슨은 실습 시간 자체를 잘게 쪼개기보다 OT와 선수요건 확인, 기관 섭외와 일정 준비, 실습 수행, 사후평가와 보고 정리의 큰 관문으로 묶습니다.", "기관실습은 출근일 나열보다 실습세미나, 방문지도, 중간점검, 사후정리 같은 구조를 우선 보여야 합니다."},
		LastLessonRule:          "마지막 lesson은 기관실습과 사후정리를 마쳐 실습 인정 직전까지 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 자격 발급, 공식 수료, 최종 학점 인정은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"OT 참석", "실습기관 찾기", "일지 양식 다운로드", "출석 규정 읽기"},
	},
	"knowledge_hobby:professional_transition:credit_bank_standard_theory": {
		Name:                    "학점은행제 표준 이론형",
		StepRoles:               []string{"setup_intro", "core_pattern", "integration_practice"},
		StageRules:              []string{"리슨은 주차별 개념 나열보다 핵심 이론 묶음, 사례 적용, 실무 연결 흐름이 보이게 구성합니다.", "중후반부에는 제도나 현장 적용 관점으로 개념을 통합하는 단계가 포함되어야 합니다."},
		LastLessonRule:          "마지막 lesson은 주요 개념을 사례와 실무 관점으로 연결해 정리하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 자격 발급, 공식 학점 인정, 현장 투입은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"용어 정의만 외우기", "이론 이름만 나열하기", "법 조항만 읽기"},
	},
	"knowledge_hobby:teaching_instruction:credit_bank_instructional_design": {
		Name:                    "학점은행제 교수설계형",
		StepRoles:               []string{"setup_intro", "structure_plan", "integration_practice", "teaching_prep"},
		StageRules:              []string{"리슨은 개념 설명만 나열하지 말고 교안, 활동계획안, 평가문항처럼 실제 설계 단위를 분명히 보여야 합니다.", "중간 단계에는 교수 원리 이해 뒤에 설계안 작성과 피드백 반영 흐름이 이어져야 합니다."},
		LastLessonRule:          "마지막 lesson은 수업안이나 평가 설계를 정리해 실제 운영 직전까지 준비하는 단계여야 합니다.",
		CompletionCriteriaRules: []string{"실제 강의 운영, 공식 자격 발급, 현장 투입은 completion_criteria로 분리합니다."},
		AtomicDisallowExamples:  []string{"교안 양식만 보기", "평가 정의만 외우기", "용어 정리만 하기"},
	},
}
